'use strict';
(()=>{
const icons={camera:'<path d="M8 6l2-3h4l2 3h4v14H4V6z"/><circle cx="12" cy="12" r="4"/>',file:'<path d="M6 3h8l4 4v14H6zM14 3v5h4M9 12h6M9 16h6"/>',text:'<path d="M4 5h16M12 5v15M8 20h8"/>'};
const icon=k=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[k]}</svg>`;
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const schoolCatalog=['Marista']; // Catálogo ilustrativo apenas desta prévia.
const app=document.getElementById('app');let state={step:1,mode:'camera',text:'',name:'',school:'',theme:'',themeMode:'known',confirmed:false,file:null,url:''};
function save(){const t=document.getElementById('essayText'),n=document.getElementById('studentName'),h=document.getElementById('theme');if(t)state.text=t.value;if(n)state.name=n.value;const school=document.getElementById('schoolName');if(school)state.school=SchoolNames.match(school.value,schoolCatalog).label;if(h)state.theme=h.value;}
function steps(){return `<div class="steps"><span class="${state.step===1?'current':''}"><b>1</b> Redação</span><i></i><span class="${state.step===2?'current':''}"><b>2</b> Tema</span><i></i><span class="${state.step===3?'current':''}"><b>3</b> Correção</span></div>`}
function home(){app.innerHTML=`<span class="eyebrow">SEU ESPAÇO DE ESCRITA</span><h1>Vamos mais longe?</h1><p>Uma redação. Uma boa conversa. Um próximo passo.</p><section class="hero"><div class="hero-top"><div><span class="eyebrow">SEM CADASTRAR TURMA</span><h2 style="margin-top:10px">Ao Vivo</h2><p>Da folha para a devolutiva.<br>Trabalhe uma redação com o aluno, ali com você.</p></div><div class="camera-tile">${icon('camera')}</div></div><div class="hero-bottom"><button class="btn" data-open="ao-vivo">${icon('camera')} Começar uma correção</button><small>Foto, PDF, Word ou texto</small></div></section><div class="section-label">Com suas turmas</div><div class="grid"><section class="card"><h2>Receber redações</h2><p>Identifique a turma, o aluno e a proposta para enviar uma redação à fila.</p><button class="btn" data-open="receber">Receber uma redação</button></section><section class="card"><h2>Seu histórico ao vivo</h2><p>As correções avulsas terão um espaço próprio, organizado por data, tema e nome opcional.</p><button class="btn" data-open="historico">Conhecer o histórico</button></section></div>`;}
function live(){app.innerHTML=`<button class="back" data-open="inicio">← Voltar ao início</button><span class="eyebrow" style="display:block">A REDAÇÃO NO CENTRO DA CONVERSA</span><h1>Ao Vivo</h1><p>Sem escola, turma ou proposta cadastrada.</p>${steps()}<section class="card" id="step"></section>`;const box=document.getElementById('step');
if(state.step===1){box.innerHTML=`<h2>Como vamos começar?</h2><p>Escolha a forma mais prática de trazer o texto.</p><div class="input-options">${[['camera','Fotografar'],['file','Enviar arquivo'],['text','Colar texto']].map(([k,l])=>`<button class="option ${state.mode===k?'selected':''}" data-mode="${k}" aria-pressed="${state.mode===k}">${icon(k)}${l}</button>`).join('')}</div>${state.mode==='text'?`<label class="field">Redação<textarea id="essayText" placeholder="Cole aqui o texto completo da redação…" maxlength="20000">${esc(state.text)}</textarea></label><p class="muted">De 80 a 20.000 caracteres.</p>`:`<div class="drop"><button class="btn ${state.mode==='camera'?'primary':''}" id="pick">${icon(state.mode)} ${state.mode==='camera'?'Abrir câmera':'Escolher arquivo'}</button><p>${state.mode==='camera'?'Fotografe a folha inteira, com foco e boa luz.':'JPG, PNG, WEBP, PDF ou Word (.docx) · até 15 MB'}</p><input hidden id="file" type="file" accept="${state.mode==='camera'?'image/*':'image/jpeg,image/png,image/webp,application/pdf,.docx'}" ${state.mode==='camera'?'capture="environment"':''}><div id="selected">${state.file?`<div class="file-name">${esc(state.file.name)}</div>${state.url?`<img class="file-preview" src="${state.url}" alt="Prévia da redação selecionada">`:'<p class="muted">Arquivo selecionado. A leitura será feita pelo serviço de correção.</p>'}`:''}</div></div>`}<label class="field">Nome do aluno <span>Opcional · não cria cadastro</span><input id="studentName" type="text" maxlength="160" placeholder="Como você quer identificar esta redação?" value="${esc(state.name)}"></label><label class="field">Escola <span>Opcional · não cria cadastro</span><input id="schoolName" aria-describedby="schoolHelp" autocomplete="off" type="text" maxlength="160" placeholder="Nome da escola, se desejar" value="${esc(state.school)}"></label><p id="schoolHelp" class="muted">Sugestões de exemplo nesta prévia: Marista. Você pode manter outro nome.</p><div id="schoolSuggestions" aria-live="polite"></div><p class="error" id="error" role="status"></p><div class="actions"><span class="muted">O arquivo permanece neste navegador durante a prévia.</span><button class="btn primary" id="next">Continuar →</button></div>`;
const schoolInput=document.getElementById('schoolName');
const suggest=()=>{const result=SchoolNames.match(schoolInput.value,schoolCatalog),host=document.getElementById('schoolSuggestions');host.replaceChildren();if(result.exact)return;result.suggestions.forEach(name=>{const button=document.createElement('button');button.type='button';button.className='btn';button.textContent='Usar '+name+'?';button.onclick=()=>{schoolInput.value=name;state.school=name;host.replaceChildren();};host.append(button);});};
schoolInput.oninput=suggest;schoolInput.onblur=()=>{const result=SchoolNames.match(schoolInput.value,schoolCatalog);if(result.exact)schoolInput.value=result.exact;};suggest();
const pick=document.getElementById('pick');if(pick){pick.onclick=()=>document.getElementById('file').click();document.getElementById('file').onchange=e=>{const f=e.target.files[0];if(!f)return;save();if(f.size>15*1024*1024||!(/\.(jpe?g|png|webp|pdf|docx)$/i.test(f.name))){document.getElementById('error').textContent='Use JPG, PNG, WEBP, PDF ou DOCX, até 15 MB.';return;}if(state.url)URL.revokeObjectURL(state.url);state.file=f;state.url=/\.(jpe?g|png|webp)$/i.test(f.name)?URL.createObjectURL(f):'';live();};}
document.getElementById('next').onclick=()=>{save();if(state.mode==='text'?state.text.trim().length<80:!state.file){document.getElementById('error').textContent=state.mode==='text'?'Cole pelo menos 80 caracteres.':'Escolha uma redação para continuar.';return;}state.step=2;live();};
}else if(state.step===2){box.innerHTML=`<h2>Qual é o tema da redação?</h2><p>O tema e o recorte orientam a análise da competência 2.</p><label class="choice"><input type="radio" name="themeMode" value="known" ${state.themeMode==='known'?'checked':''}>Tenho o tema ou o enunciado original</label><label class="choice"><input type="radio" name="themeMode" value="infer" ${state.themeMode==='infer'?'checked':''}>Quero identificar o tema pelo texto</label>${state.themeMode==='infer'?`<div class="note"><b>Sugestão da IA, confirmação do professor.</b><br>Sem a proposta original, não é possível comprovar fuga ao tema. A C2 será avaliada em relação ao recorte confirmado.</div><button class="btn" id="example">Ver exemplo de sugestão</button><p class="muted">Exemplo ilustrativo; esta prévia não analisa seu arquivo.</p>`:''}<label class="field">${state.themeMode==='infer'?'Tema e recorte a confirmar':'Tema ou enunciado'}<textarea id="theme" placeholder="Ex.: Desafios para fortalecer a educação midiática entre os jovens brasileiros">${esc(state.theme)}</textarea></label><label class="choice"><input id="confirmed" type="checkbox" ${state.confirmed?'checked':''}>Conferi o tema e o recorte que orientarão a correção.</label><p class="error" id="error" role="status"></p><div class="actions"><button class="btn ghost" id="back">← Redação</button><button class="btn primary" id="next">Revisar e continuar →</button></div>`;
box.querySelectorAll('[name=themeMode]').forEach(r=>r.onchange=()=>{save();state.themeMode=r.value;state.confirmed=false;live()});document.getElementById('theme').oninput=()=>{state.confirmed=false;document.getElementById('confirmed').checked=false;};document.getElementById('confirmed').onchange=e=>state.confirmed=e.target.checked;
const example=document.getElementById('example');if(example)example.onclick=()=>{state.theme='Exemplo: Desafios para fortalecer a educação midiática entre os jovens brasileiros diante da desinformação digital.';state.confirmed=false;live();};document.getElementById('back').onclick=()=>{save();state.step=1;live()};document.getElementById('next').onclick=()=>{save();if(state.theme.trim().length<10||!state.confirmed){document.getElementById('error').textContent='Informe um tema e confirme o recorte para continuar.';return;}state.step=3;live();};
}else{box.innerHTML=`<h2>Pronto para uma boa devolutiva</h2><p>Confira o que vai orientar a correção.</p><div class="summary-row"><span>Aluno</span><b>${esc(state.name)||'Sem identificação'}</b></div><div class="summary-row"><span>Escola</span><b>${esc(state.school)||'Não informada'}</b></div><div class="summary-row"><span>Redação</span><b>${state.mode==='text'?'Texto colado':esc(state.file?.name)}</b></div><div class="summary-row"><span>Tema</span><b>${esc(state.theme)}</b></div><div class="summary-row"><span>Critério C2</span><b>${state.themeMode==='known'?'Proposta informada pelo professor':'Recorte inferido e confirmado · sem aferição da proposta original'}</b></div><div class="note">Você receberá notas por competência, ponto forte, prioridade de melhoria e próximo passo. A revisão final é do professor.</div><div class="note"><b>Compartilhe quando quiser.</b><br>Após revisar, você poderá compartilhar a devolutiva aqui ou pelo histórico: WhatsApp, copiar link ou outras opções do celular. Nome do aluno e escola são opcionais.</div><div class="actions"><button class="btn ghost" id="back">← Ajustar tema</button><button class="btn primary" disabled>Iniciar correção</button></div><p class="muted">Prévia: análise, saldo e cobrança ainda não conectados. Na versão ativa, o custo será mostrado antes da confirmação.</p>`;document.getElementById('back').onclick=()=>{state.step=2;live();};}
}
function page(p){save();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));if(p==='ao-vivo')live();else if(p==='receber')app.innerHTML=`<button class="back" data-open="inicio">← Voltar ao início</button><span class="eyebrow" style="display:block">COM SUAS TURMAS</span><h1>Receber redações</h1><p>O Ao Vivo vinculado a turmas ganha um nome mais claro.</p><section class="card" style="margin-top:24px"><h2>O fluxo conhecido continua aqui</h2><p>Escola → turma → aluno → proposta → foto ou imagem → fila de correções.</p><div class="note">Na aplicação, esta entrada abrirá a ferramenta atual, preservando seus vínculos e registros.</div><button class="btn primary" data-open="ao-vivo">Quero corrigir sem turma</button></section>`;else if(p==='historico')app.innerHTML=`<button class="back" data-open="inicio">← Voltar ao início</button><h1>Histórico ao vivo</h1><div class="card empty">${icon('file')}<h2>Um espaço para cada conversa</h2><p>Aqui ficarão as redações avulsas, seus temas e devolutivas.<br>As redações ficam privadas. Após revisar, você poderá compartilhar uma devolutiva quando quiser, sem precisar fazer uma nova correção.</p><button class="btn primary" data-open="ao-vivo">Começar uma correção</button></div>`;else home();window.scrollTo?.(0,0);}
document.querySelectorAll('[data-camera]').forEach(e=>e.innerHTML=icon('camera'));document.addEventListener('click',e=>{const b=e.target.closest('[data-page],[data-open],[data-mode]');if(!b)return;if(b.dataset.mode){save();state.mode=b.dataset.mode;live();}else page(b.dataset.page||b.dataset.open)});document.querySelector('.brand').onclick=e=>{e.preventDefault();page('inicio')};page('inicio');
})();
