'use strict';
const BASE='https://huccxcpwoydwuisrmboc.supabase.co',KEY='sb_publishable_KzojVBVP3GvVbSgO_w0mUA_-s8r7VdR',SK='versao-e12-session-v1';
const MUTATIONS_ENABLED=false,PAID_AI_ENABLED=true;
const API={live:'live-correction-api',proposal:'proposal-api',official:'official-correction-api',ai:'ai-correction-api',studentDash:'student-dashboard-api',studentProp:'student-proposals-api',studentSub:'student-submission-api',admin:'admin-base-api'};
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate=v=>{if(!v)return'—';try{return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(v))}catch{return'—'}};
const one=x=>Array.isArray(x)?x[0]:x;
const S={session:null,profile:null,route:null,cache:{},student:null};
const PERF={requests:0,boot_started:performance.now()}; window.__VERSAO_E12__={state:S,perf:PERF,mutations:MUTATIONS_ENABLED,paid_ai:PAID_AI_ENABLED};
function saveSession(s){localStorage.setItem(SK,JSON.stringify(s))}function readSession(){try{return JSON.parse(localStorage.getItem(SK)||'null')}catch{return null}}function clearSession(){localStorage.removeItem(SK)}
function authHeaders(token,json=true){const h={apikey:KEY,Authorization:'Bearer '+token};if(json)h['Content-Type']='application/json';return h}
async function request(url,options={}){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),url.includes('/functions/v1/')?180000:20000);try{return await fetch(url,{...options,signal:controller.signal})}catch(e){if(e.name==='AbortError')throw Error('A conexão demorou a responder. Tente novamente.');throw e}finally{clearTimeout(timeout)}}
async function signIn(email,password,save=true){PERF.requests++;const r=await request(BASE+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error_description||d.msg||d.message||'Não foi possível entrar.');const s={access_token:d.access_token,refresh_token:d.refresh_token,expires_at:Math.floor(Date.now()/1000)+(d.expires_in||3600),user:d.user};if(save)saveSession(s);return s}
async function refreshSession(s){if(!s?.refresh_token)return null;PERF.requests++;const r=await request(BASE+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:s.refresh_token})});if(!r.ok)return null;const d=await r.json();const n={access_token:d.access_token,refresh_token:d.refresh_token||s.refresh_token,expires_at:Math.floor(Date.now()/1000)+(d.expires_in||3600),user:d.user||s.user};saveSession(n);return n}
async function ensure(){let s=S.session;if(!s)throw Error('Sessão ausente.');if(!s.expires_at||s.expires_at<Math.floor(Date.now()/1000)+60)s=await refreshSession(s);if(!s){clearSession();throw Error('Sessão expirada.');}S.session=s;return s}
async function rest(path){const s=await ensure();PERF.requests++;const r=await request(BASE+'/rest/v1/'+path,{headers:authHeaders(s.access_token,false)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||d.hint||'Falha ao consultar dados.');return d}
async function edge(slug,body={},retried=false){const s=await ensure();PERF.requests++;const r=await request(`${BASE}/functions/v1/${slug}`,{method:'POST',headers:authHeaders(s.access_token),body:JSON.stringify(body)});if(r.status===401&&!retried){S.session=await refreshSession(S.session);if(S.session)return edge(slug,body,true)}const d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw Error(typeof d.error==='string'?d.error:'Falha na operação.');return d}
async function profile(){const id=S.session?.user?.id;if(!id)throw Error('Usuário não identificado.');const p=(await rest(`profiles?id=eq.${encodeURIComponent(id)}&select=id,full_name,email,role,approval_status,organization_id,teacher_scope`))[0];if(!p||p.approval_status!=='approved')throw Error('Conta sem acesso aprovado.');if(!['super_admin','teacher','student'].includes(p.role))throw Error('Perfil sem acesso ao VERSÃO.');S.profile=p;return p}
function showOnly(id){['boot','auth','shell'].forEach(x=>$(x).classList.toggle('hidden',x!==id))}
function toast(msg){document.querySelector('.toast')?.remove();const d=document.createElement('div');d.className='toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),3600)}
function safeMessage(action){toast(`${action} validado no ambiente isolado. Nenhum dado foi gravado na produção.`)}
const NAV_TEACHER=[['home','Início'],['proposals','Propostas'],['live','Ao vivo'],['correction','Correção'],['ranking','Ranking']];
const NAV_STUDENT=[['student-home','Início'],['student-proposals','Propostas'],['student-essays','Minhas redações'],['student-evolution','Evolução'],['student-account','Conta']];
function buildNav(){let nav=S.profile.role==='student'?[...NAV_STUDENT]:[...NAV_TEACHER];if(S.profile.role==='super_admin')nav.push(['management','Gestão']);$('nav').innerHTML=nav.map(([r,l])=>`<button data-route="${r}"><span class="dot"></span>${l}</button>`).join('');$('nav').onclick=e=>{const b=e.target.closest('[data-route]');if(b){navigate(b.dataset.route);closeDrawer()}};$('identity').innerHTML=`<b>${esc(S.profile.full_name||S.profile.email||'Usuário')}</b>${esc(S.profile.role==='super_admin'?'Super Admin':S.profile.role==='teacher'?'Professor':'Aluno')}`}
function openDrawer(){$('sidebar').classList.add('open');$('drawerShade').classList.remove('hidden')}function closeDrawer(){$('sidebar').classList.remove('open');$('drawerShade').classList.add('hidden')}
function header(title,sub,action=''){return `<div class="page-head"><div><span class="page-kicker">VERSÃO · ETAPA 12</span><h1>${esc(title)}</h1><p>${esc(sub)}</p></div>${action}</div>`}
function setActive(route){document.querySelectorAll('#nav [data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===route))}
async function navigate(route){S.route=route;setActive(route);$('view').innerHTML='<div class="empty">Carregando...</div>';try{const map={home:renderHome,proposals:renderProposals,live:renderLive,correction:renderCorrection,ranking:renderRanking,management:renderManagement,'student-home':renderStudentHome,'student-proposals':renderStudentProposals,'student-essays':renderStudentEssays,'student-evolution':renderStudentEvolution,'student-account':renderStudentAccount};if(!map[route])throw Error('Área não disponível.');await map[route]()}catch(e){$('view').innerHTML=header('Não foi possível carregar','O módulo permaneceu isolado e nenhuma gravação foi realizada.')+`<div class="card"><b>${esc(e.message||e)}</b></div>`}}

async function teacherQueue(force=false){if(!force&&S.cache.queue)return S.cache.queue;const d=await edge(API.live,{action:'queue'});S.cache.queue=d.items||[];return S.cache.queue}
async function teacherProposals(force=false){if(!force&&S.cache.teacherProps)return S.cache.teacherProps;const d=await edge(API.proposal,{action:'bootstrap'});S.cache.teacherProps=d;return d}
async function orgNames(){if(S.cache.orgNames)return S.cache.orgNames;const a=await rest('organizations?select=id,name&order=name');S.cache.orgNames=new Map(a.map(x=>[x.id,x.name]));return S.cache.orgNames}
function statusLabel(row){if(row.score?.is_approved)return['Aprovada','ok'];if(row.job_status==='processing')return['Em correção','warn'];return['Aguardando oficial','crimson']}
