'use strict';
(function(){
 const baseResult=renderAiResult,baseManual=manualCorrection,baseSave=saveManual;
 let tab='all',search='';
 const css=document.createElement('style');css.textContent=`
 .cx{max-width:820px;margin:auto}.cx-tabs{display:flex;gap:8px;overflow:auto;margin:12px 0}.cx-tab{border:1px solid #ddd4d1;background:#fff;border-radius:11px;padding:9px 12px;font-weight:700;white-space:nowrap}.cx-tab.on{background:#991d1f;color:#fff;border-color:#991d1f}.cx-search{width:100%;height:44px;border:1px solid #ddd4d1;border-radius:12px;padding:0 13px;margin-bottom:14px}.cx-list{display:grid;gap:14px}.cx-card,.cx-panel{background:#fff;border:1px solid #e5dfdc;border-radius:18px;padding:18px;box-shadow:0 7px 24px rgba(57,31,28,.05)}.cx-name{font-size:18px;font-weight:800}.cx-theme{color:#6f6967;margin-top:5px;line-height:1.35}.cx-meta{font-size:14px;color:#888;margin-top:6px}.cx-ch{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:14px 0}.cx-ch>div{background:#fbfaf9;border:1px solid #ebe5e2;border-radius:13px;padding:10px 12px}.cx-ch small{display:block;color:#817a77;margin-bottom:5px}.cx-pill{display:inline-flex;border-radius:999px;padding:6px 9px;font-size:12px;font-weight:800;background:#f1f1f2;color:#5f6167}.cx-pill.processing{background:#fff2cf;color:#9a6200}.cx-pill.validation{background:#e9f2ff;color:#285e9b}.cx-pill.approved,.cx-pill.published{background:#e6f5eb;color:#247043}.cx-pill.failed{background:#fde9e7;color:#9d251e}.cx-pill.draft{background:#fff4df;color:#8a5d12}.cx-actions{display:grid;gap:8px}.cx-actions .btn{width:100%;min-height:45px;justify-content:center}.cx-flow{max-width:720px;margin:auto}.cx-back{margin-bottom:12px}.cx-title{font-size:24px;margin:18px 0 5px}.cx-sub{color:#716b68;margin:0 0 16px}.cx-info{background:#f3f6fa;border-radius:13px;padding:13px;margin:13px 0}.cx-info.err{background:#fff0ee;color:#7d2924}.cx-process,.cx-result{text-align:center;padding:14px 0}.cx-ring{width:108px;height:108px;border-radius:50%;margin:5px auto 18px;background:conic-gradient(#991d1f 0 38%,#f1dada 38%);display:grid;place-items:center}.cx-ring:after{content:'✎';width:78px;height:78px;border-radius:50%;background:#fff;color:#991d1f;display:grid;place-items:center;font-size:32px}.cx-steps{display:grid;grid-template-columns:repeat(3,1fr);margin:20px 0}.cx-step:before{content:'';display:block;width:28px;height:28px;border-radius:50%;background:#eee;margin:0 auto 6px}.cx-step.done:before{content:'✓';background:#258957;color:#fff;line-height:28px}.cx-step.now:before{content:'2';background:#991d1f;color:#fff;line-height:28px}.cx-flow .split{display:block!important}.cx-flow .essay-pane{display:none!important}.cx-manual .essay-pane{display:block!important;margin-bottom:12px}.cx-flow .box{border:0!important;box-shadow:none!important;max-width:none!important}.cx-flow .box-head,.cx-flow .box-body{padding-left:0!important;padding-right:0!important}@media(max-width:640px){.cx-ch{grid-template-columns:1fr}.cx-card,.cx-panel{padding:15px}}
 `;document.head.appendChild(css);
 const aiText={uncorrected:'Não iniciada',processing:'Em análise',validation:'Pronta para revisar',approved:'Publicada',failed:'Falhou'},manText={not_started:'Não iniciada',draft:'Rascunho',published:'Publicada'};
 function draft(id){try{return !!localStorage.getItem(manualKey(id))}catch{return false}}
 function astate(r){const s=r?._channels?.ai?.status??r?.job_status;return s==='approved'?'approved':['queued','processing'].includes(s)?'processing':s==='completed'?'validation':['failed','cancelled'].includes(s)?'failed':'uncorrected'}
 function mstate(r){return r?._channels?.manual?.status==='published'?'published':draft(r?.submission_id)?'draft':'not_started'}
 correctionState=r=>astate(r);
 const row=id=>(S.cache.correctionRows||[]).find(x=>x.submission_id===id)||{};
 const pill=(t,s)=>`<span class="cx-pill ${s}">${esc(t)}</span>`;
 const channels=r=>`<div class="cx-ch"><div><small>Correção com IA</small>${pill(aiText[astate(r)],astate(r))}</div><div><small>Correção manual</small>${pill(manText[mstate(r)],mstate(r))}</div></div>`;
 async function load(rs){try{const s=await ensure(),x=await fetch(BASE+'/functions/v1/correction-channels-api',{method:'POST',headers:authHeaders(s.access_token),body:JSON.stringify({action:'statuses',submission_ids:rs.map(r=>r.submission_id)})}),d=await x.json();if(!x.ok||d.error)throw Error(d.error||'Falha');rs.forEach(r=>{r._channels=d.channels?.[r.submission_id]||{ai:{status:r.job_status},manual:{status:'not_started'}};r.job_status=r._channels.ai?.status||null})}catch(e){console.warn(e);rs.forEach(r=>r._channels={ai:{status:r.job_status},manual:{status:'not_started'}})}}
 function card(r){const id=esc(r.submission_id),a=astate(r),m=mstate(r),ai=a==='processing'?'Acompanhar IA':a==='validation'?'Revisar IA':a==='approved'?'Ver correção com IA':a==='failed'?'Tentar IA novamente':'Corrigir com IA',mn=m==='published'?'Ver correção manual':m==='draft'?'Continuar correção manual':'Corrigir manualmente';return `<article class="cx-card"><div class="cx-name">${esc(r.student_name||'Aluno')}</div><div class="cx-theme">${esc(r.theme||'')}</div><div class="cx-meta">${esc(r.class_name||'')} ${r.orgName||r.organization_name?'· '+esc(r.orgName||r.organization_name):''}</div>${channels(r)}<div class="cx-actions"><button class="btn primary" data-cx-ai="${id}">${ai}</button><button class="btn soft-btn" data-cx-man="${id}">${mn}</button><button class="btn ghost" data-cx-view="${id}">Ver redação</button></div></article>`}
 function draw(){const q=S.cache.correctionRows||[],n=search.trim().toLowerCase(),a=q.filter(r=>(tab==='all'||astate(r)===tab)&&(!n||String(r.student_name||'').toLowerCase().includes(n)||String(r.theme||'').toLowerCase().includes(n)));$('cxList').innerHTML=a.length?a.map(card).join(''):'<div class="empty">Nenhuma redação encontrada.</div>';document.querySelectorAll('.cx-tab').forEach(b=>b.classList.toggle('on',b.dataset.tab===tab))}
 renderCorrection=async nav=>{const q=await teacherQueue(true);q.forEach(r=>r.orgName=r.organization_name||r.orgName||'Sem instituição');await load(q);if(!navigationCurrent(nav))return;S.cache.correctionRows=q;const c={all:q.length,processing:q.filter(r=>astate(r)==='processing').length,validation:q.filter(r=>astate(r)==='validation').length,failed:q.filter(r=>astate(r)==='failed').length};$('view').innerHTML=`<section class="cx"><h1>Fila de correções</h1><p class="muted">IA e manual são canais independentes para a mesma redação.</p><div class="cx-tabs"><button class="cx-tab" data-tab="all">Todas (${c.all})</button><button class="cx-tab" data-tab="processing">IA em análise (${c.processing})</button><button class="cx-tab" data-tab="validation">IA pronta (${c.validation})</button><button class="cx-tab" data-tab="failed">Falhas (${c.failed})</button></div><input id="cxSearch" class="cx-search" placeholder="Buscar aluno ou tema..."><div id="cxList" class="cx-list"></div></section>`;draw();$('cxSearch').oninput=e=>{search=e.target.value;draw()};$('view').onclick=e=>{let b=e.target.closest('[data-tab]');if(b){tab=b.dataset.tab;draw();return}b=e.target.closest('[data-cx-view]');if(b)return showEssay(b.dataset.cxView);b=e.target.closest('[data-cx-man]');if(b)return showManual(b.dataset.cxMan);b=e.target.closest('[data-cx-ai]');if(b){const id=b.dataset.cxAi,s=astate(row(id));if(s==='uncorrected'){showAi(id,false);return aiCorrection(id,{retry:true})}return s==='failed'?failure(id):showAi(id,true)}}};
 function shell(r,body){$('view').innerHTML=`<section class="cx-flow"><button class="btn ghost cx-back" id="cxBack">← Voltar para correções</button><div class="cx-panel"><div class="cx-name">${esc(r.student_name||'Redação')}</div><div class="cx-theme">${esc(r.theme||'')}</div>${channels(r)}${body}</div></section>`;$('cxBack').onclick=()=>navigate('correction')}
 function showEssay(id){const r=row(id);shell(r,`<h2 class="cx-title">Redação</h2><div id="cxEssay"></div>`);openEssay(id,$('cxEssay'))}
 function confirmAi(id){const r=row(id);shell(r,`<h2 class="cx-title">Correção com IA</h2><p class="cx-sub">Confirme o envio para a Inteligência VERSÃO.</p><div class="cx-info"><b>Esta correção usa 1 crédito.</b><br>O resultado será preparado para sua revisão.</div><div class="cx-actions"><button class="btn primary" id="cxSend">Enviar para correção</button><button class="btn soft-btn" id="cxCancel">Cancelar</button></div>`);$('cxCancel').onclick=()=>navigate('correction');$('cxSend').onclick=async()=>{showAi(id,false);await aiCorrection(id,{retry:true})}}
 async function showAi(id,readOnly){const r=row(id);shell(r,`<div id="slot-${esc(id)}"></div>`);$('slot-'+id).innerHTML=`<div class="split"><div class="essay-pane" id="aiEssay-${esc(id)}"></div><div class="box"><div class="box-body"><div class="cx-process"><div class="cx-ring"></div><h2>Analisando redação</h2><p>A Inteligência VERSÃO está preparando a correção.</p><div class="cx-steps"><div class="cx-step done">Recebida</div><div class="cx-step now">Analisando</div><div class="cx-step">Finalizando</div></div><div class="cx-info">Você pode sair desta tela. A correção continuará em segundo plano.</div></div></div></div></div>`;if(readOnly)return aiCorrection(id,{readOnly:true})}
 function failure(id){const r=row(id);shell(r,`<div id="slot-${esc(id)}"><div class="box"><div class="box-body"><div class="cx-result"><h2>Correção com IA não concluída</h2><p>A redação continua salva.</p><div class="cx-info err">O crédito da tentativa com falha é devolvido.</div><div class="cx-actions"><button class="btn primary" id="cxRetry">Tentar IA novamente</button><button class="btn soft-btn" id="cxManual">Corrigir manualmente</button><button class="btn ghost" id="cxView">Ver redação</button></div></div></div></div></div>`);$('cxRetry').onclick=async()=>{showAi(id,false);await aiCorrection(id,{retry:true})};$('cxManual').onclick=()=>showManual(id);$('cxView').onclick=()=>showEssay(id)}
 function seedManual(id,r){if(draft(id))return;const s=r?._channels?.manual?.data,d=blankManual();if(s){for(const[c]of CC){d.scores[c]=Number(s.competencies?.[c]?.score??s.competencies?.[c]??160);d.just[c]=String(s.competency_justifications?.[c]||s.competencies?.[c]?.justification||'')}d.dev=String(s.detailed_analysis?.deviations_rules||'');d.prio=String(s.improvement_priority||'');d.feed=String(s.overall_feedback||'');d.auth=String(s.authorship_validation||'');d.obs=String(s.observations||'')}try{localStorage.setItem(manualKey(id),JSON.stringify(d))}catch{}}
 function showManual(id){const r=row(id);seedManual(id,r);shell(r,`<h2 class="cx-title">Correção manual</h2><p class="cx-sub">Este canal é independente da correção com IA.</p><div class="cx-manual"><div id="slot-${esc(id)}"></div></div>`);baseManual(id);$('view').onclick=async e=>{let b=e.target.closest('[data-save-manual]');if(b)return baseSave(b.dataset.saveManual,false);b=e.target.closest('[data-publish-manual]');if(b)return baseSave(b.dataset.publishManual,true)}}
 function friendly(m){const t=String(m||'');if(/credit_balance_exhausted|saldo|balance/i.test(t))return'O serviço de IA está temporariamente sem saldo. A redação permanece salva e o crédito foi devolvido.';if(/mutually exclusive|file_id|filename|input\[/i.test(t))return'O arquivo não pôde ser processado pela IA. A redação permanece salva e o crédito foi devolvido.';return t||'Não foi possível concluir a correção com IA.'}
 aiQueueStatus=(id,status)=>{S.cache.queue=null;const r=row(id);if(r){r.job_status=status;r._channels=r._channels||{};r._channels.ai={...(r._channels.ai||{}),status}}};
 aiNotice=(ctx,message,retry=false,waiting=false)=>{if(!aiPanelCurrent(ctx))return;if(waiting){const sec=Math.max(0,Math.floor((Date.now()-Date.parse(ctx.startedAt||new Date().toISOString()))/1000));ctx.box.innerHTML=`<div class="box-body"><div class="cx-process"><div class="cx-ring"></div><h2>Analisando redação</h2><p>A Inteligência VERSÃO está preparando a correção.</p><div class="cx-steps"><div class="cx-step done">Recebida</div><div class="cx-step now">Analisando</div><div class="cx-step">Finalizando</div></div><div class="cx-info"><b>Tempo decorrido: ${sec} s</b><br>Você pode sair desta tela.</div></div></div>`;return}if(retry){ctx.box.innerHTML=`<div class="box-body"><div class="cx-result"><h2>Correção com IA não concluída</h2><p>${esc(friendly(message))}</p><div class="cx-actions"><button class="btn primary" data-ai-retry>Tentar IA novamente</button><button class="btn soft-btn" data-man-fallback>Corrigir manualmente</button></div></div></div>`;ctx.box.querySelector('[data-ai-retry]').onclick=()=>aiCorrection(ctx.id,{retry:true});ctx.box.querySelector('[data-man-fallback]').onclick=()=>showManual(ctx.id);return}ctx.box.innerHTML=`<div class="box-body"><div class="cx-info">${esc(friendly(message))}</div></div>`};
 renderAiResult=(id,job,official,usage,r)=>{const box=$('slot-'+id)?.querySelector('.box');if(!box)return;if(box.dataset.full==='1')return baseResult(id,job,official,usage,r);const approved=job?.status==='approved',n=Number(job?.result?.total_score??official?.total_score);aiQueueStatus(id,approved?'approved':'completed');box.innerHTML=`<div class="box-body"><div class="cx-result"><h2>Correção com IA concluída</h2><p>${approved?'Correção publicada.':'Pronta para sua revisão.'}</p>${Number.isFinite(n)?`<div class="cx-info"><b>${n} / 1000</b></div>`:''}<div class="cx-actions"><button class="btn primary" data-full>${approved?'Ver correção com IA':'Revisar correção'}</button><button class="btn soft-btn" data-original>Ver redação original</button></div></div><div id="cxOriginal"></div></div>`;box.querySelector('[data-full]').onclick=()=>{box.dataset.full='1';baseResult(id,job,official,usage,r)};box.querySelector('[data-original]').onclick=()=>openEssay(id,box.querySelector('#cxOriginal'))};
})();