'use strict';
(function(){
 const ROOT='proposalRecipientApprovedV4',STYLE='proposalRecipientApprovedV4Style';
 const state={data:[],selected:new Set(),mode:'org',editingId:null,timer:null,saving:false};
 const html=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function css(){if(document.getElementById(STYLE))return;const s=document.createElement('style');s.id=STYLE;s.textContent=`
 .recipient-v4-section #pvScope{border:0!important;padding:0!important;background:transparent!important}.recipient-v4-section #pvScope>.field,.recipient-v4-section>label:has(#pvAll),.recipient-v4-section .proposal-v3-mode-note,.recipient-v4-section #proposalAllRecipientsV3,.recipient-v4-section #pvSummary{display:none!important}.recipient-v4-active .proposal-v2-footer{display:none!important}
 .recipient-v4{display:grid;gap:10px}.recipient-v4-tabs{display:flex;border-bottom:1px solid #eee6e3}.recipient-v4-tab{flex:1;border:0;background:transparent;padding:10px 12px 12px;font:inherit;font-weight:750;color:#667085;border-bottom:2px solid transparent}.recipient-v4-tab.active{color:#8f1519;border-bottom-color:#a90813}
 .recipient-v4-all,.recipient-v4-org,.recipient-v4-classflat{border:1px solid #e7dfdc;border-radius:14px;background:#fff;overflow:hidden}.recipient-v4-all{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:11px;align-items:center;padding:14px 15px;background:#fff8f7;border-color:#e3aaa5;color:#8d171b;cursor:pointer}.recipient-v4-all strong{font-size:14px}.recipient-v4-all span{font-size:12px;color:#7d6d6b;text-align:right}
 .recipient-v4-head{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:11px;align-items:center;padding:14px 15px}.recipient-v4-title{display:grid;gap:2px}.recipient-v4-title strong{font-size:15px;color:#202936}.recipient-v4-title span{font-size:12px;color:#7a7f89}.recipient-v4-toggle{border:0;background:transparent;width:34px;height:34px;border-radius:8px;font-size:18px;color:#4a5565;cursor:pointer}.recipient-v4-body{border-top:1px solid #eee8e5;padding:4px 15px 10px 47px;display:grid}.recipient-v4-org[data-collapsed='1'] .recipient-v4-body{display:none}.recipient-v4-org[data-collapsed='1'] .recipient-v4-toggle{transform:rotate(180deg)}
 .recipient-v4-check{appearance:none;width:21px;height:21px;border:2px solid #a8adb5;border-radius:6px;background:#fff;display:grid;place-items:center;margin:0;cursor:pointer}.recipient-v4-check:checked{border-color:#a90813;background:#a90813}.recipient-v4-check:checked:after{content:'✓';color:#fff;font-size:13px;font-weight:900}.recipient-v4-class-check:checked{border-color:#2f75db;background:#2f75db}
 .recipient-v4-row{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:10px;align-items:center;min-height:46px;border-bottom:1px solid #f2edeb;color:#303846;cursor:pointer}.recipient-v4-row:last-child{border-bottom:0}.recipient-v4-row>span:first-of-type{font-weight:650}.recipient-v4-meta{font-size:12px;color:#7a7f89;white-space:nowrap}.recipient-v4-classflat{padding:0 15px}
 .recipient-v4-bottom{display:grid;grid-template-columns:1fr auto;gap:14px;align-items:center;margin-top:12px;padding-top:13px;border-top:1px solid #eee6e3}.recipient-v4-selected{display:grid;gap:2px;color:#667085;font-size:12px}.recipient-v4-selected strong{font-size:16px;color:#202936}.recipient-v4-bottom .btn{min-width:180px;min-height:46px}
 @media(max-width:760px){.recipient-v4-all{grid-template-columns:auto 1fr;padding:13px}.recipient-v4-all span{grid-column:2;text-align:left;margin-top:-3px}.recipient-v4-head{padding:13px}.recipient-v4-body{padding:4px 13px 10px 44px}.recipient-v4-bottom{grid-template-columns:1fr}.recipient-v4-bottom .btn{width:100%;min-width:0}}
 `;document.head.appendChild(s)}
 function collect(){const org=document.getElementById('pvOrg'),box=document.getElementById('pvClassBox');if(!org||!box)return null;const original=org.value,initialAll=!!document.getElementById('pvAll')?.checked;const initialSelected=new Set([...box.querySelectorAll('input[name="target"]:checked')].map(x=>String(x.value)));const data=[];for(const opt of [...org.options].filter(o=>o.value)){org.value=opt.value;org.dispatchEvent(new Event('change',{bubbles:true}));const classes=[...box.querySelectorAll('input[name="target"]')].map(x=>({id:String(x.value),name:(x.closest('label')?.textContent||x.value).trim()}));data.push({id:String(opt.value),name:opt.textContent.trim(),classes})}org.value=original;org.dispatchEvent(new Event('change',{bubbles:true}));state.selected=initialSelected;if(initialAll)data.flatMap(o=>o.classes).forEach(c=>state.selected.add(c.id));return data}
 function allClasses(){return state.data.flatMap(o=>o.classes.map(c=>({...c,orgId:o.id,orgName:o.name})))}
 function renderList(){const list=document.querySelector(`#${ROOT} [data-list]`);if(!list)return;if(state.mode==='class'){list.innerHTML=`<div class="recipient-v4-classflat">${allClasses().map(c=>`<label class="recipient-v4-row"><input class="recipient-v4-check recipient-v4-class-check" type="checkbox" name="target" value="${html(c.id)}" data-class="${html(c.id)}" ${state.selected.has(c.id)?'checked':''}><span>${html(c.name)}</span><span class="recipient-v4-meta">${html(c.orgName)}</span></label>`).join('')}</div>`;return}list.innerHTML=state.data.map((o,i)=>`<section class="recipient-v4-org" data-org="${html(o.id)}" data-collapsed="${i<2?'0':'1'}"><div class="recipient-v4-head"><input class="recipient-v4-check" type="checkbox" data-org-check="${html(o.id)}"><div class="recipient-v4-title"><strong>${html(o.name)}</strong><span>${o.classes.length} turma${o.classes.length===1?'':'s'}</span></div><button type="button" class="recipient-v4-toggle" data-toggle>⌃</button></div><div class="recipient-v4-body">${o.classes.map(c=>`<label class="recipient-v4-row"><input class="recipient-v4-check recipient-v4-class-check" type="checkbox" name="target" value="${html(c.id)}" data-class="${html(c.id)}" ${state.selected.has(c.id)?'checked':''}><span>${html(c.name)}</span><span></span></label>`).join('')||'<div class="muted" style="padding:10px 0">Nenhuma turma disponível.</div>'}</div></section>`).join('');sync()}
 function sync(){const root=document.getElementById(ROOT);if(!root)return;root.querySelectorAll('[data-class]').forEach(x=>x.checked=state.selected.has(String(x.dataset.class)));state.data.forEach(o=>{const b=root.querySelector(`[data-org-check="${CSS.escape(o.id)}"]`);if(!b)return;const n=o.classes.filter(c=>state.selected.has(c.id)).length;b.checked=o.classes.length>0&&n===o.classes.length;b.indeterminate=n>0&&n<o.classes.length});const all=allClasses();const ab=root.querySelector('[data-all]');if(ab){ab.checked=all.length>0&&state.selected.size===all.length;ab.indeterminate=state.selected.size>0&&state.selected.size<all.length}const h=document.getElementById('pvAll');if(h)h.checked=all.length>0&&state.selected.size===all.length;const map=new Map(all.map(c=>[c.id,c])),first=[...state.selected][0],org=document.getElementById('pvOrg');if(org&&first&&!org.disabled)org.value=map.get(first)?.orgId||org.value;const out=root.querySelector('.recipient-v4-selected strong');if(out)out.textContent=`${state.selected.size} turma${state.selected.size===1?'':'s'} selecionada${state.selected.size===1?'':'s'}`;const cont=root.querySelector('[data-continue]');if(cont)cont.disabled=state.selected.size===0}
 function mount(){const form=document.getElementById('proposalV2Form'),scope=document.getElementById('pvScope'),box=document.getElementById('pvClassBox');if(!form||!scope||!box||document.getElementById(ROOT))return;const data=collect();if(!data||!form.isConnected)return;state.data=data;const section=scope.closest('.proposal-v2-section');section?.classList.add('recipient-v4-section');form.classList.add('recipient-v4-active');const p=section?.querySelector('header p');if(p)p.textContent='Selecione as instituições e as turmas que receberão esta proposta.';document.getElementById('pvAll')?.closest('label')?.setAttribute('hidden','');document.getElementById('pvOrg')?.closest('label')?.setAttribute('hidden','');box.innerHTML=`<div id="${ROOT}" class="recipient-v4"><div class="recipient-v4-tabs"><button type="button" class="recipient-v4-tab active" data-mode="org">Por instituição</button><button type="button" class="recipient-v4-tab" data-mode="class">Por turma</button></div><label class="recipient-v4-all"><input class="recipient-v4-check" type="checkbox" data-all><strong>Selecionar todas as instituições e turmas</strong><span>${data.length} instituições · ${allClasses().length} turmas disponíveis</span></label><div data-list></div><div class="recipient-v4-bottom"><div class="recipient-v4-selected"><span>Selecionadas:</span><strong>0 turmas selecionadas</strong></div><button type="button" class="btn primary" data-continue>Continuar →</button></div></div>`;const root=document.getElementById(ROOT);renderList();root.addEventListener('click',e=>{const mode=e.target.closest('[data-mode]');if(mode){state.mode=mode.dataset.mode;root.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));renderList();return}const t=e.target.closest('[data-toggle]');if(t){const c=t.closest('[data-org]');c.dataset.collapsed=c.dataset.collapsed==='1'?'0':'1';return}if(e.target.closest('[data-continue]'))document.getElementById('pvPublish')?.click()});root.addEventListener('change',e=>{if(e.target.matches('[data-all]')){state.selected.clear();if(e.target.checked)allClasses().forEach(c=>state.selected.add(c.id));renderList();return}if(e.target.matches('[data-org-check]')){const o=state.data.find(x=>x.id===e.target.dataset.orgCheck);o?.classes.forEach(c=>e.target.checked?state.selected.add(c.id):state.selected.delete(c.id));renderList();return}if(e.target.matches('[data-class]')){const id=String(e.target.dataset.class);e.target.checked?state.selected.add(id):state.selected.delete(id);sync()}});sync()}
 document.addEventListener('click',e=>{const edit=e.target.closest?.('[data-edit]');if(edit)state.editingId=edit.dataset.edit||null;if(e.target.closest?.('#proposalNew'))state.editingId=null},true);
 function schedule(){clearTimeout(state.timer);state.timer=setTimeout(()=>{try{mount()}catch(err){console.error('[VERSÃO] Destinatários v4:',err)}},80)}
 const view=document.getElementById('view');if(view)new MutationObserver(schedule).observe(view,{subtree:true,childList:true});document.addEventListener('DOMContentLoaded',schedule,{once:true});css();schedule();
})();