'use strict';
async function studentDashboard(force=false){if(!force&&S.student?.dashboard)return S.student.dashboard;const d=await edge(API.studentDash,{});S.student=S.student||{};S.student.dashboard=d;return d}
async function studentProposals(force=false){if(!force&&S.student?.proposals)return S.student.proposals;const d=await edge(API.studentProp,{});S.student=S.student||{};S.student.proposals=d;return d}
async function renderStudentHome(navigation){const d=await studentDashboard(true);if(!navigationCurrent(navigation))return;$('view').innerHTML=header('Início','Seu painel de redações e evolução.')+`<section class="grid cols4"><div class="card metric"><small>Nota atual</small><b>${d.summary.current_score??'—'}</b></div><div class="card metric"><small>Média</small><b>${d.summary.average_score??'—'}</b></div><div class="card metric"><small>Melhor nota</small><b>${d.summary.best_score??'—'}</b></div><div class="card metric"><small>Redações corrigidas</small><b>${d.summary.approved_count||0}</b></div></section><div class="card" style="margin-top:12px"><b>${esc(d.student.preferred_name||d.student.full_name)}</b><div class="item-meta">${esc(d.organization?.name||'')} · ${(d.classes||[]).map(c=>esc(c.name)).join(' · ')}</div><button class="btn primary" id="studentSendShortcut">Enviar redação</button></div>`;$('studentSendShortcut').onclick=()=>navigate('student-proposals')}
async function renderStudentProposals(navigation){const [p,dash]=await Promise.all([studentProposals(true),studentDashboard()]);const ids=(p.proposals||[]).map(x=>x.id),states=ids.length?(await edge(API.studentSub,{action:'states',round_ids:ids})).states||[]:[],sm=new Map(states.map(s=>[s.round_id,s]));if(!navigationCurrent(navigation))return;$('view').innerHTML=header('Propostas','Envie uma única página e acompanhe o status da redação.')+`<div class="list" id="spList">${(p.proposals||[]).map(r=>{const st=sm.get(r.id),sub=st?.submission,editable=st?.editable===true;return `<article class="student-card"><div class="item-top"><div><div class="item-title">R${esc(r.number??'—')} · ${esc(r.theme)}</div>${r.due_date?`<div class="item-meta">Prazo: ${fmtDate(r.due_date)}</div>`:""}</div><span class="pill ${sub?.status==='approved'?'ok':sub?'warn':'crimson'}">${sub?.status==='approved'?'Aprovada':sub?'Enviada':'Disponível'}</span></div><p class="muted">${esc(r.proposal_command||'')}</p>${r.understand_prompt?`<div class="safe-note"><b>Entenda o que o tema está pedindo</b><br>${esc(r.understand_prompt)}</div>`:''}${(r.motivators||[]).map((m,i)=>`<section class="safe-note"><strong>Texto motivador ${i+1}${m.title?' — '+esc(m.title):''}</strong><p class="demo-text-preview">${esc(m.body||'')}</p>${m.asset_url&&/^https:\/\//i.test(m.asset_url)?`<img src="${esc(m.asset_url)}" alt="${esc(m.caption||m.title||'Imagem do texto motivador')}" style="max-width:100%;height:auto" loading="lazy">`:''}${m.source_url&&/^https?:\/\//i.test(m.source_url)?`<a href="${esc(m.source_url)}" target="_blank" rel="noopener noreferrer">${esc(m.source_label||'Consultar fonte')}</a>`:esc(m.source_label||'')}</section>`).join('')}<div class="item-actions"><button class="btn soft-btn" data-student-prop="${r.id}" ${editable?'':'disabled'}>${sub?'Substituir imagem':'Enviar redação'}</button>${sub?`<button class="btn ghost" data-student-view="${sub.id}">Abrir minha redação</button>`:''}</div><div id="spr-${r.id}"></div></article>`}).join('')||'<div class="empty">Nenhuma proposta disponível.</div>'}</div>`;$('spList').onclick=e=>studentProposalClick(e,sm)}
async function studentProposalClick(e,sm){let b=e.target.closest('[data-student-prop]');if(b){const id=b.dataset.studentProp,slot=$('spr-'+id),st=sm.get(id),listRoot=$('spList');if(st?.editable!==true)return toast('A correção já começou e o arquivo não pode mais ser substituído.');slot.innerHTML=`<div class="drop" style="margin-top:10px"><b>Uma página</b><p class="safe-note">${PHOTO_GUIDANCE}</p><input id="sf-${id}" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"><div id="sfp-${id}" class="preview" style="min-height:180px;margin-top:10px"><div class="preview-placeholder">Escolha uma imagem.</div></div><p data-photo-status role="status"></p><label class="photo-confirm"><input data-photo-confirm type="checkbox" disabled> Conferi todas as linhas: estão legíveis, sem cortes, sombras ou reflexos.</label><button class="btn primary" data-student-final="${id}" disabled style="margin-top:10px">Enviar para correção</button></div>`;const f=$('sf-'+id),send=slot.querySelector('[data-student-final]'),checked=slot.querySelector('[data-photo-confirm]'),photoStatus=slot.querySelector('[data-photo-status]');let photoSequence=0,acceptedFile=null;
checked.onchange=()=>{send.disabled=!acceptedFile||!checked.checked};
f.onchange=async()=>{
 const sequence=++photoSequence,file=f.files?.[0];acceptedFile=null;send.disabled=true;checked.checked=false;checked.disabled=true;if(!file)return;
 if(!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type)||file.size>15*1024*1024){f.value='';return toast('Use JPG, PNG, WEBP ou PDF de uma página, até 15 MB.')}
 if(file.type==='application/pdf'){$('sfp-'+id).innerHTML=`<p>PDF selecionado: ${esc(file.name)}. Abra o arquivo e confira se há apenas uma página legível.</p>`;photoStatus.textContent='PDF requer conferência manual da legibilidade.';acceptedFile=file;checked.disabled=false;return}
 const url=URL.createObjectURL(file);$('sfp-'+id).innerHTML=`<img src="${url}" alt="Prévia">`;const img=$('sfp-'+id).querySelector('img');img.onload=img.onerror=()=>URL.revokeObjectURL(url);
 photoStatus.textContent='Verificando a imagem...';
 try{const warnings=await inspectEssayPhoto(file);if(sequence!==photoSequence||!slot.isConnected)return;
 photoStatus.textContent=warnings.length?warnings.join(' '):'Verificação inicial concluída. Confira a prévia: a análise automática não garante legibilidade.';
 if(!warnings.length){acceptedFile=file;checked.disabled=false;}
 }catch(error){if(sequence===photoSequence)photoStatus.textContent=error.message}
};send.onclick=async()=>{
 if(send.disabled||!checked.checked)return;const file=acceptedFile;if(!file||file!==f.files?.[0])return;
 send.disabled=true;f.disabled=true;checked.disabled=true;send.textContent='Enviando...';
 try{await uploadEssay(API.studentSub,{action:'upload',round_id:id},file);await edge(API.studentSub,{action:'finalize',round_id:id});const state=await edge(API.studentSub,{action:'state',round_id:id});sm.set(id,state);S.cache={};S.student=null;send.textContent='Enviado';toast('Redação enviada para correção.');if($('spList')===listRoot&&S.route==='student-proposals')await navigate('student-proposals');}
 catch(error){send.disabled=false;send.textContent='Enviar para correção';toast(error.message||'Falha no envio.')}
 finally{f.disabled=false;checked.disabled=false}
};return}b=e.target.closest('[data-student-view]');if(b){const id=b.dataset.studentView;try{const d=await edge(API.studentSub,{action:'view_file',submission_id:id});const host=e.target.closest('.student-card');let v=host.querySelector('.viewer');if(v)v.remove();v=document.createElement('div');v.className='viewer';v.innerHTML=String(d.file.mime_type).startsWith('image')?`<img src="${esc(d.file.signed_url)}" alt="Minha redação">`:`<a class="btn soft-btn" href="${esc(d.file.signed_url)}" target="_blank" rel="noopener noreferrer">Abrir PDF da redação</a>`;host.appendChild(v)}catch(err){toast(err.message)}}}
async function renderStudentEssays(navigation){const d=await studentDashboard(true);if(!navigationCurrent(navigation))return;$('view').innerHTML=header('Minhas redações','Notas e devolutivas só aparecem depois da aprovação do professor.')+`<div class="list" id="seList">${(d.submissions||[]).map(s=>{const a=s.approved_score;return `<article class="student-submission"><div class="item-top"><div><div class="item-title">${s.round?`R${esc(s.round.number??'—')} · ${esc(s.round.theme)}`:'Redação'}</div><div class="item-meta">Recebida em ${fmtDate(s.received_at)}</div></div><span class="pill ${a?'ok':'warn'}">${a?'Aprovada':'Em acompanhamento'}</span></div>${a?`<div class="grid cols3" style="margin-top:10px"><div><small class="muted">Nota</small><div class="student-score">${a.total_score}</div></div><div><small class="muted">Prioridade</small><p>${esc(a.improvement_priority||'—')}</p></div><div><small class="muted">Devolutiva</small><p>${esc(a.feedback||'—')}</p></div></div><div class="grid cols4">${['C1','C2','C3','C4','C5'].map(c=>`<div class="card metric"><small>${c}</small><b>${a.competencies?.[c]??'—'}</b><p>${esc(a.competency_justifications?.[c]||'')}</p>${a.detailed_analysis?.competency_improvements?.[c]?`<p><strong>Próximo passo:</strong> ${esc(a.detailed_analysis.competency_improvements[c])}</p>`:''}</div>`).join('')}</div>`:'<div class="safe-note" style="margin-top:10px">Nota, competências e devolutiva serão liberadas após a aprovação do professor.</div>'}${a?studentCorrectionDetails(a.detailed_analysis):''}${s.has_file?`<div class="item-actions"><button class="btn ghost" data-own-view="${s.id}">Abrir redação</button></div>`:''}</article>`}).join('')||'<div class="empty">Você ainda não possui redações.</div>'}</div>`;$('seList').onclick=async e=>{const b=e.target.closest('[data-own-view]');if(!b)return;try{const d=await edge(API.studentSub,{action:'view_file',submission_id:b.dataset.ownView}),host=b.closest('.student-submission');let v=host.querySelector('.viewer');if(v)v.remove();v=document.createElement('div');v.className='viewer';v.innerHTML=String(d.file.mime_type).startsWith('image')?`<img src="${esc(d.file.signed_url)}" alt="Minha redação">`:'<div class="empty">Arquivo não-imagem.</div>';host.appendChild(v)}catch(err){toast(err.message)}}}
async function renderStudentEvolution(navigation){const d=await studentDashboard(true),ev=d.evolution||[];if(!navigationCurrent(navigation))return;$('view').innerHTML=header('Evolução','Histórico construído somente com correções oficialmente aprovadas.')+`<section class="grid cols2"><div class="box"><div class="box-head"><h2>Evolução geral</h2></div><div class="box-body timeline">${ev.length?ev.map(x=>`<div class="timeline-row"><b>${x.round?`R${esc(x.round.number??'—')}`:fmtDate(x.approved_at)}</b><div class="bar"><i style="width:${Math.max(0,Math.min(100,Number(x.total_score||0)/10))}%"></i></div><span>${x.total_score}</span></div>`).join(''):'<div class="empty">Ainda não há correções aprovadas suficientes.</div>'}</div></div><div class="box"><div class="box-head"><h3>Último desempenho por competência</h3></div><div class="box-body comps">${['C1','C2','C3','C4','C5'].map(c=>{const v=ev.at(-1)?.competencies?.[c];return `<div class="comp-ind ${c.toLowerCase()}"><div class="comp-ind-head"><b>${c}</b><span>${v??'—'}</span></div><div class="track"><i style="width:${v==null?0:Math.min(100,Number(v)/2)}%"></i></div></div>`}).join('')}</div></div></section>`}
async function renderStudentAccount(navigation){const d=await studentDashboard();if(!navigationCurrent(navigation))return;$('view').innerHTML=header('Conta','Seu acesso ao VERSÃO.')+`<section class="card"><h2>${esc(d.student.full_name)}</h2><p>${esc(d.organization?.name||'')}</p><p class="muted">${(d.classes||[]).map(c=>esc(c.name)).join(' · ')}</p><p>Você entra com o código da turma e seu PIN individual. Se precisar de outro PIN, peça ao professor. Suas redações e notas serão mantidas.</p></section>`;}


function studentCorrectionDetails(d={}){
 const deviations=Array.isArray(d.c1_deviations)?d.c1_deviations:[],checks=Array.isArray(d.repertoire_checks)?d.repertoire_checks:[];
 return `<details class="ai-section"><summary>Ver análise aprovada pelo professor</summary>${d.syntax_assessment?`<h4>Estrutura sintática</h4><p>${esc(d.syntax_assessment)}</p>`:''}<h4>Desvios e orientações</h4>${deviations.map(x=>`<p><strong>${esc(x.original)}</strong> → ${esc(x.correction)}<br>${esc(x.rule)} · ${esc(x.location)}</p>`).join('')||`<p>${esc(d.deviations_rules||'Não há ocorrências registradas nesta devolutiva.')}</p>`}${checks.length?`<h4>Repertórios</h4>${checks.map(x=>`<p><strong>${esc(x.reference)}</strong> · ${esc(x.classification)}<br>${esc(x.analysis)} ${/^https?:\/\//i.test(x.source_url||'')?`<a href="${esc(x.source_url)}" target="_blank" rel="noopener noreferrer">Consultar fonte</a>`:''}</p>`).join('')}`:''}<h4>C5 — Os cinco elementos da proposta de intervenção</h4><p>Veja o que foi identificado na sua redação. Os elementos devem estar relacionados ao problema discutido.</p>${[['action','1. Ação — O que será feito?','A medida proposta para enfrentar o problema.'],['agent','2. Agente — Quem fará?','Quem será responsável por executar a ação.'],['means','3. Meio/modo — Como será feito?','O recurso, instrumento ou procedimento usado para realizar a ação.'],['purpose','4. Finalidade/efeito — Para quê?','O objetivo ou resultado que a ação pretende alcançar.'],['detail','5. Detalhamento — Que informação torna a proposta mais específica?','Uma explicação, exemplo ou especificação de um dos elementos anteriores.']].map(([key,label,help])=>`<div class="ai-section"><p><strong>${label}</strong><br><small>${help}</small></p><p>${esc(d.c5_check?.[key]||'Não há análise registrada para este elemento nesta correção.')}</p></div>`).join('')}<h4>Verificações adicionais</h4><p><strong>Respeito aos direitos humanos:</strong> ${esc(d.c5_check?.human_rights||'Não registrado.')}</p><p><strong>Relação com os argumentos:</strong> ${esc(d.c5_check?.argument_alignment||'Não registrado.')}</p></details>`;
}
