'use strict';
async function studentDashboard(force=false){if(!force&&S.student?.dashboard)return S.student.dashboard;const d=await edge(API.studentDash,{});S.student=S.student||{};S.student.dashboard=d;return d}
async function studentProposals(force=false){if(!force&&S.student?.proposals)return S.student.proposals;const d=await edge(API.studentProp,{});S.student=S.student||{};S.student.proposals=d;return d}
async function renderStudentEssays(navigation){const d=await studentDashboard(true);if(!navigationCurrent(navigation))return;$('view').innerHTML=header('Minhas redações','Notas e devolutivas só aparecem depois da aprovação do professor.')+`<div class="list" id="seList">${[...(d.submissions||[])].sort((a,b)=>new Date(b.received_at)-new Date(a.received_at)).map((s,index)=>{const a=s.approved_score;return `${index===1?'<details class="ai-section"><summary>Redações anteriores</summary>':''}<article class="student-submission">${index===0?'<h2>Redação mais recente</h2>':''}<div class="item-top"><div><div class="item-title">${s.round?`R${esc(s.round.number??'—')} · ${esc(s.round.theme)}`:'Redação'}</div><div class="item-meta">Recebida em ${fmtDate(s.received_at)}</div></div><span class="pill ${a?'ok':'warn'}">${a?'Aprovada':'Aguardando correção'}</span></div>${a?'<details class="ai-section"><summary>Ver correção</summary>':''}${a?.detailed_analysis?.report_format==='essential-v1'?studentEssentialReport(a):a?`<div class="grid cols3" style="margin-top:10px"><div><small class="muted">Nota</small><div class="student-score">${a.total_score}</div></div><div><small class="muted">Prioridade</small><p>${esc(a.improvement_priority||'—')}</p></div><div><small class="muted">Devolutiva</small><p>${esc(a.feedback||'—')}</p></div></div><div class="grid cols4">${['C1','C2','C3','C4','C5'].map(c=>`<div class="card metric"><small>${c}</small><b>${a.competencies?.[c]??'—'}</b><p>${esc(a.competency_justifications?.[c]||'')}</p>${a.detailed_analysis?.competency_improvements?.[c]?`<p><strong>Próximo passo:</strong> ${esc(a.detailed_analysis.competency_improvements[c])}</p>`:''}</div>`).join('')}</div>`:'<div class="safe-note" style="margin-top:10px">Nota, competências e devolutiva serão liberadas após a aprovação do professor.</div>'}${a&&a.detailed_analysis?.report_format!=='essential-v1'?studentCorrectionDetails(a.detailed_analysis):''}${a?'</details>':''}${s.has_file?`<div class="item-actions"><button class="btn ghost" data-own-view="${s.id}">Ver redação enviada</button></div>`:''}</article>${index===(d.submissions||[]).length-1&&index>0?'</details>':''}`}).join('')||'<div class="empty">Você ainda não possui redações.</div>'}</div>`;$('seList').onclick=async e=>{const b=e.target.closest('[data-own-view]');if(!b)return;try{const d=await edge(API.studentSub,{action:'view_file',submission_id:b.dataset.ownView}),host=b.closest('.student-submission');let v=host.querySelector('.viewer');if(v)v.remove();v=document.createElement('div');v.className='viewer';v.innerHTML=String(d.file.mime_type).startsWith('image')?`<img src="${esc(d.file.signed_url)}" alt="Minha redação">`:'<div class="empty">Arquivo não-imagem.</div>';host.appendChild(v)}catch(err){toast(err.message)}}}
async function renderStudentEvolution(navigation){const d=await studentDashboard(true),ev=d.evolution||[];if(!navigationCurrent(navigation))return;$('view').innerHTML=header('Evolução','Histórico construído somente com correções oficialmente aprovadas.')+`<section class="grid cols2"><div class="box"><div class="box-head"><h2>Evolução geral</h2></div><div class="box-body timeline">${ev.length?ev.map(x=>`<div class="timeline-row"><b>${x.round?`R${esc(x.round.number??'—')}`:fmtDate(x.approved_at)}</b><div class="bar"><i style="width:${Math.max(0,Math.min(100,Number(x.total_score||0)/10))}%"></i></div><span>${x.total_score}</span></div>`).join(''):'<div class="empty">Ainda não há correções aprovadas suficientes.</div>'}</div></div><div class="box"><div class="box-head"><h3>Último desempenho por competência</h3></div><div class="box-body comps">${['C1','C2','C3','C4','C5'].map(c=>{const v=ev.at(-1)?.competencies?.[c];return `<div class="comp-ind ${c.toLowerCase()}"><div class="comp-ind-head"><b>${c}</b><span>${v??'—'}</span></div><div class="track"><i style="width:${v==null?0:Math.min(100,Number(v)/2)}%"></i></div></div>`}).join('')}</div></div></section>`}
async function renderStudentAccount(navigation){const d=await studentDashboard();if(!navigationCurrent(navigation))return;$('view').innerHTML=header('Conta','Seu acesso ao VERSÃO.')+`<section class="card"><h2>${esc(d.student.full_name)}</h2><p>${esc(d.organization?.name||'')}</p><p class="muted">${(d.classes||[]).map(c=>esc(c.name)).join(' · ')}</p><p>Você entra com o código da turma e seu PIN individual. Se precisar de outro PIN, peça ao professor. Suas redações e notas serão mantidas.</p></section>`;}


function studentCorrectionDetails(d={}){
 const deviations=Array.isArray(d.c1_deviations)?d.c1_deviations:[],checks=Array.isArray(d.repertoire_checks)?d.repertoire_checks:[];
 if(d.report_format==='essential-v1')return `<section class="ai-section"><h4>Ponto forte</h4><p>${esc(d.main_strength||'Não informado')}</p><h4>Desvios</h4>${deviations.map(x=>`<p><b>Trecho:</b> ${esc(x.original)}<br><b>Tipo:</b> ${esc(x.category)}<br><b>Explicação:</b> ${esc(x.rule)}<br><b>Sugestão:</b> ${esc(x.correction)}</p>`).join('')||(Array.isArray(d.c1_deviations)?'<p>Nenhum desvio confirmado.</p>':`<p>${esc(d.deviations_rules||'Desvios não disponíveis nesta versão da correção.')}</p>`)}<h4>C5</h4>${[['action','Ação'],['agent','Agente'],['means','Meio/modo'],['purpose','Finalidade/efeito'],['detail','Detalhamento']].map(([key,label])=>`<p>${label}: ${esc(d.c5_check?.[key]||'Não informado')}</p>`).join('')}<h4>Próximo passo</h4><p>${esc(d.next_step||'Não informado')}</p></section>`;
 return `<details class="ai-section"><summary>Ver análise aprovada pelo professor</summary>${d.syntax_assessment?`<h4>Estrutura sintática</h4><p>${esc(d.syntax_assessment)}</p>`:''}<h4>Desvios e orientações</h4>${deviations.map(x=>`<p><strong>${esc(x.original)}</strong> → ${esc(x.correction)}<br>${esc(x.rule)} · ${esc(x.location)}</p>`).join('')||`<p>${esc(d.deviations_rules||'Não há ocorrências registradas nesta devolutiva.')}</p>`}${checks.length?`<h4>Repertórios</h4>${checks.map(x=>`<p><strong>${esc(x.reference)}</strong> · ${esc(x.classification)}<br>${esc(x.analysis)} ${/^https?:\/\//i.test(x.source_url||'')?`<a href="${esc(x.source_url)}" target="_blank" rel="noopener noreferrer">Consultar fonte</a>`:''}</p>`).join('')}`:''}<h4>C5 — Os cinco elementos da proposta de intervenção</h4><p>Veja o que foi identificado na sua redação. Os elementos devem estar relacionados ao problema discutido.</p>${[['action','1. Ação — O que será feito?','A medida proposta para enfrentar o problema.'],['agent','2. Agente — Quem fará?','Quem será responsável por executar a ação.'],['means','3. Meio/modo — Como será feito?','O recurso, instrumento ou procedimento usado para realizar a ação.'],['purpose','4. Finalidade/efeito — Para quê?','O objetivo ou resultado que a ação pretende alcançar.'],['detail','5. Detalhamento — Que informação torna a proposta mais específica?','Uma explicação, exemplo ou especificação de um dos elementos anteriores.']].map(([key,label,help])=>`<div class="ai-section"><p><strong>${label}</strong><br><small>${help}</small></p><p>${esc(d.c5_check?.[key]||'Não há análise registrada para este elemento nesta correção.')}</p></div>`).join('')}<h4>Verificações adicionais</h4><p><strong>Respeito aos direitos humanos:</strong> ${esc(d.c5_check?.human_rights||'Não registrado.')}</p><p><strong>Relação com os argumentos:</strong> ${esc(d.c5_check?.argument_alignment||'Não registrado.')}</p></details>`;
}

function studentEssentialReport(a){
        const d=a.detailed_analysis||{},codes=['C1','C2','C3','C4','C5'];
        return `<section class="ai-section"><h4>Nota e competências</h4><div class="student-score">${Number(a.total_score)} / 1000</div><div class="ai-competencies">${codes.map(c=>`<div class="ai-comp"><div class="ai-comp-head"><b>${c}</b><span>${Number(a.competencies?.[c])}</span></div><p>${esc(a.competency_justifications?.[c]||'Sem justificativa registrada.')}</p></div>`).join('')}</div><h4>C5</h4>${[['action','Ação'],['agent','Agente'],['means','Meio/modo'],['purpose','Finalidade/efeito'],['detail','Detalhamento']].map(([k,l])=>`<p>${l}: ${esc(d.c5_check?.[k]||'Não informado')}</p>`).join('')}</section><section class="ai-section"><h4>Ponto forte</h4><p>${esc(d.main_strength||'Não informado')}</p></section><section class="ai-section"><h4>Prioridade de melhoria</h4><p>${esc(a.improvement_priority||'Não informada')}</p></section><section class="ai-section"><h4>Desvios</h4>${(d.c1_deviations||[]).map(x=>`<p><b>Trecho:</b> ${esc(x.original)}<br><b>Tipo:</b> ${esc(x.category)}<br><b>Explicação:</b> ${esc(x.rule)}<br><b>Sugestão:</b> ${esc(x.correction)}</p>`).join('')||(Array.isArray(d.c1_deviations)?'<p>Nenhum desvio confirmado.</p>':`<p>${esc(d.deviations_rules||'Desvios não disponíveis nesta versão da correção.')}</p>`)}</section><section class="ai-section"><h4>Próximo passo</h4><p>${esc(a.feedback||d.next_step||'Não informado')}</p></section>`;
}
