'use strict';
(function(){
 const STYLE_ID='teacherProposalsV3Style';
 const AXES=['Educação','Tecnologia','Meio ambiente','Saúde','Cultura','Cidadania e direitos humanos','Trabalho e economia'];
 let renderToken=0;

 function css(){
  if(document.getElementById(STYLE_ID))return;
  const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
  .proposal-v3{max-width:1120px;display:grid;gap:16px}.proposal-v3-tabs{display:flex;gap:22px;border-bottom:1px solid #eee3e0}.proposal-v3-tab{border:0;background:transparent;padding:11px 2px 12px;border-bottom:2px solid transparent;font:inherit;font-weight:800;color:#667085;cursor:pointer}.proposal-v3-tab.active{color:#8f1519;border-color:#a90813}
  .proposal-v3-toolbar{display:grid;grid-template-columns:minmax(0,1fr) 210px;gap:10px}.proposal-v3-toolbar input,.proposal-v3-toolbar select{min-height:44px}.proposal-v3-list{display:grid;gap:12px}.proposal-v3-card{border:1px solid #e7dfdc;border-radius:15px;background:#fff;padding:16px 18px;display:grid;grid-template-columns:minmax(0,1fr) auto;grid-template-areas:'main status' 'actions actions';gap:10px 14px;box-shadow:0 3px 12px rgba(32,41,54,.035)}.proposal-v3-main{grid-area:main;min-width:0;display:grid;gap:7px}.proposal-v3-title{font-size:16px;font-weight:850;line-height:1.35;color:#172033}.proposal-v3-chips{display:flex;gap:7px;flex-wrap:wrap}.proposal-v3-chip{display:inline-flex;padding:4px 9px;border-radius:999px;background:#f2f6fb;color:#355b87;font-size:11px;font-weight:750}.proposal-v3-command{margin:0;color:#667085;font-size:12.5px;line-height:1.45;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.proposal-v3-meta{font-size:12px;color:#667085}.proposal-v3-status{grid-area:status;align-self:start;justify-self:end;border-radius:999px;padding:5px 9px;font-size:11px;font-weight:800}.proposal-v3-status.ok{background:#e8f7ee;color:#147946}.proposal-v3-status.warn{background:#fff4d6;color:#9a6800}.proposal-v3-status.hidden{background:#eef1f5;color:#596273}.proposal-v3-actions{grid-area:actions;display:flex;justify-content:flex-end;gap:8px;border-top:1px solid #f4efed;padding-top:10px}.proposal-v3-actions .btn{min-height:36px;padding:7px 12px;font-size:12px;min-width:88px}
  .proposal-v3-editor{display:grid;gap:18px}.proposal-v3-section{border:1px solid #e9e1de;border-radius:16px;padding:20px;background:#fff;display:grid;gap:16px;box-shadow:0 7px 24px rgba(16,24,40,.035)}.proposal-v3-section>header h2{margin:0;font-size:18px}.proposal-v3-section>header p{margin:5px 0 0;color:#667085;font-size:13px;line-height:1.5}.proposal-v3-axis{border:1px solid #e3a7a1;background:#fff8f7;border-radius:14px;padding:14px 16px;color:#7f1717;font-weight:800}.proposal-v3-axis select{margin-top:8px;background:#fff!important;border-color:#dca09a!important;font-weight:700}.proposal-v3-axis small{display:block;margin-top:6px;color:#756765;font-weight:600}.proposal-v3-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.proposal-v3-ai{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:18px;align-items:center;border:1px solid #e7aaa4;background:linear-gradient(115deg,#fff7f6,#fffafa 65%,#fbe9e7);border-radius:16px;padding:17px}.proposal-v3-ai h3{margin:0 0 5px;color:#8d1418}.proposal-v3-ai p{margin:0;color:#667085;font-size:13px}.proposal-v3-ai .btn{min-height:46px;background:#a90813;color:#fff;border-color:#a90813;font-weight:800}.proposal-v3-motivator{border:1px solid #e5dfdc;border-radius:14px;padding:16px;display:grid;gap:12px}.proposal-v3-motivator textarea{min-height:145px}.proposal-v3-footer{display:flex;justify-content:flex-end;gap:10px;flex-wrap:wrap;position:sticky;bottom:0;background:linear-gradient(to top,#fff 78%,rgba(255,255,255,.7));padding:14px 0 2px;z-index:2}
  .recipient-v3{display:grid;gap:10px}.recipient-v3-tabs{display:flex;border-bottom:1px solid #eee6e3}.recipient-v3-tab{flex:1;border:0;background:transparent;padding:10px 12px 12px;font:inherit;font-weight:750;color:#667085;border-bottom:2px solid transparent;cursor:pointer}.recipient-v3-tab.active{color:#8f1519;border-bottom-color:#a90813}.recipient-v3-all,.recipient-v3-org,.recipient-v3-flat{border:1px solid #e7dfdc;border-radius:14px;background:#fff;overflow:hidden}.recipient-v3-all{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:11px;align-items:center;padding:14px 15px;background:#fff8f7;border-color:#e3aaa5;color:#8d171b;cursor:pointer}.recipient-v3-all strong{font-size:14px}.recipient-v3-all span{font-size:12px;color:#7d6d6b;text-align:right}.recipient-v3-head{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:11px;align-items:center;padding:14px 15px}.recipient-v3-title{display:grid;gap:2px}.recipient-v3-title strong{font-size:15px;color:#202936}.recipient-v3-title span{font-size:12px;color:#7a7f89}.recipient-v3-toggle{border:0;background:transparent;width:34px;height:34px;border-radius:8px;font-size:18px;color:#4a5565;cursor:pointer}.recipient-v3-body{border-top:1px solid #eee8e5;padding:4px 15px 10px 47px;display:grid}.recipient-v3-org[data-collapsed='1'] .recipient-v3-body{display:none}.recipient-v3-org[data-collapsed='1'] .recipient-v3-toggle{transform:rotate(180deg)}.recipient-v3-check{appearance:none;width:21px;height:21px;border:2px solid #a8adb5;border-radius:6px;background:#fff;display:grid;place-items:center;margin:0;cursor:pointer}.recipient-v3-check:checked{border-color:#a90813;background:#a90813}.recipient-v3-check:checked:after{content:'✓';color:#fff;font-size:13px;font-weight:900}.recipient-v3-class-check:checked{border-color:#2f75db;background:#2f75db}.recipient-v3-row{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:10px;align-items:center;min-height:46px;border-bottom:1px solid #f2edeb;color:#303846;cursor:pointer}.recipient-v3-row:last-child{border-bottom:0}.recipient-v3-row>span:first-of-type{font-weight:650}.recipient-v3-meta{font-size:12px;color:#7a7f89;white-space:nowrap}.recipient-v3-flat{padding:0 15px}.recipient-v3-bottom{display:grid;grid-template-columns:1fr auto;gap:14px;align-items:center;margin-top:12px;padding-top:13px;border-top:1px solid #eee6e3}.recipient-v3-selected{display:grid;gap:2px;color:#667085;font-size:12px}.recipient-v3-selected strong{font-size:16px;color:#202936}.recipient-v3-bottom .btn{min-width:180px;min-height:46px}
  .proposal-v3-preview{display:grid;gap:16px;max-width:900px;margin:0 auto}.proposal-v3-preview-card{border:1px solid #eadfdb;border-radius:18px;background:#fff;padding:20px;box-shadow:0 8px 24px rgba(16,24,40,.04);display:grid;gap:16px}.proposal-v3-preview-theme{font-size:21px;font-weight:850;line-height:1.3;color:#111827}.proposal-v3-understand{border:1px solid #f0d4d0;background:#fff7f6;border-radius:14px;padding:16px;white-space:pre-wrap;color:#475467}.proposal-v3-mot-list{display:grid;gap:8px}.proposal-v3-mot{border:1px solid #e6e0dd;border-radius:11px;padding:12px 14px;display:grid;gap:3px}.proposal-v3-mot span{color:#667085;font-size:12px}.proposal-v3-dest{background:#f7f8fa;border-radius:12px;padding:13px 14px;color:#475467;font-size:13px}.proposal-v3-preview-actions{display:grid;grid-template-columns:1fr 1fr 1.35fr;gap:10px;position:sticky;bottom:0;background:linear-gradient(to top,#fff 78%,rgba(255,255,255,.75));padding:14px 0 2px}
  .proposal-ai-loader{position:fixed;inset:0;z-index:20000;background:#fffafa;display:grid;place-items:center}.proposal-ai-loader-card{width:min(520px,calc(100vw - 34px));background:#fff;border:1px solid #f0e4e1;border-radius:24px;padding:36px 30px;box-shadow:0 22px 70px rgba(113,25,31,.10);text-align:center;display:grid;gap:18px;justify-items:center}.proposal-ai-loader-ring{width:96px;height:96px;border-radius:50%;border:10px solid #f1dadd;border-top-color:#a90813;animation:proposalSpin 1s linear infinite}.proposal-ai-loader-card h2{margin:0}.proposal-ai-loader-card p{margin:0;color:#667085}@keyframes proposalSpin{to{transform:rotate(360deg)}}
  @media(max-width:760px){.proposal-v3-toolbar,.proposal-v3-grid,.proposal-v3-ai{grid-template-columns:1fr}.proposal-v3-section{padding:16px}.proposal-v3-card{grid-template-columns:1fr auto;padding:14px}.proposal-v3-actions{display:grid;grid-template-columns:repeat(3,minmax(0,1fr))}.proposal-v3-actions .btn{min-width:0;padding:8px 6px}.recipient-v3-all{grid-template-columns:auto 1fr;padding:13px}.recipient-v3-all span{grid-column:2;text-align:left;margin-top:-3px}.recipient-v3-head{padding:13px}.recipient-v3-body{padding:4px 13px 10px 44px}.recipient-v3-bottom{grid-template-columns:1fr}.recipient-v3-bottom .btn{width:100%;min-width:0}.proposal-v3-preview-actions{grid-template-columns:1fr}.proposal-v3-preview-card{padding:15px}.proposal-v3-preview-theme{font-size:18px}}
  @media(max-width:430px){.proposal-v3-actions{grid-template-columns:1fr}}
  `;document.head.appendChild(s);
 }

 const statusOf=r=>r.status==='closed'?'Oculta':r.is_visible_to_students?'Publicada':'Rascunho';
 const signature=r=>JSON.stringify([r.theme||'',r.thematic_axis||'',r.proposal_command||'',r.understand_prompt||'',statusOf(r),(r._motivators||[]).map(m=>[m.title,m.body,m.source_label,m.source_url])]);
 const allClasses=institutions=>institutions.flatMap(o=>(o.classes||[]).map(c=>({...c,orgId:o.id,orgName:o.name})));
 function actionMessage(message,title='Ação concluída'){if(typeof actionAlert==='function')actionAlert(message,title);else toast(message)}
 function loader(){const d=document.createElement('div');d.className='proposal-ai-loader';d.innerHTML='<div class="proposal-ai-loader-card"><div class="proposal-ai-loader-ring"></div><h2>Criando proposta com IA...</h2><p>Organizando tema, comando e textos motivadores.</p></div>';document.body.appendChild(d);return()=>d.remove()}
 async function exactTargets(roundId,classIds){const session=await ensure();const r=await fetch(`${BASE}/rest/v1/rpc/set_canonical_proposal_class_targets_exact`,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({p_round:roundId,p_class_ids:classIds})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||d.error||'Não foi possível atualizar os destinatários.');return d}

 async function renderDemoProposalsV3(navigation){
  css();const token=++renderToken;
  const data=await edge(API.proposal,{action:'bootstrap'});if(token!==renderToken||!navigationCurrent(navigation))return;
  const institutions=(data.organizations||[]).map(o=>({...o,classes:data.classes_by_org?.[o.id]||[]}));
  const classMap=new Map(allClasses(institutions).map(c=>[String(c.id),c]));
  const details=await Promise.all((data.recent||[]).map(async r=>{try{const d=await edge(API.proposal,{action:'get',round_id:r.id});return {...r,...d.proposal,_motivators:d.motivators||[],targets:(d.targets||[]).map(t=>t.class_id).filter(Boolean)}}catch{return {...r,_motivators:[],targets:[]}}}));
  if(token!==renderToken||!navigationCurrent(navigation))return;
  const groups=new Map();details.forEach(r=>{const k=signature(r),g=groups.get(k)||[];g.push(r);groups.set(k,g)});
  let proposals=[...groups.values()].map(g=>{const first=g[0],targets=[...new Set(g.flatMap(x=>x.targets||[]))];return {...first,_ids:g.map(x=>x.id),targets,status:statusOf(first)}});

  $('view').innerHTML=header('Propostas','Crie e publique propostas para suas instituições.')+`<section class="proposal-v3"><nav class="proposal-v3-tabs"><button class="proposal-v3-tab" id="pvTabCreate" type="button">Criar proposta</button><button class="proposal-v3-tab active" id="pvTabCreated" type="button">Propostas criadas</button></nav><div id="pvWorkspace"></div><div id="pvListArea"><div class="proposal-v3-toolbar"><input id="pvSearch" type="search" placeholder="Buscar por título, tema ou palavra-chave..."><select id="pvFilter"><option value="all">Todos os status</option><option value="published">Publicadas</option><option value="draft">Rascunhos</option><option value="hidden">Ocultas</option></select></div><p id="pvCount" class="muted"></p><div id="pvList" class="proposal-v3-list"></div></div></section>`;
  const workspace=$('pvWorkspace'),listArea=$('pvListArea');let editing=null,writing=false,generationId=null;
  const setView=v=>{const editor=v==='editor';workspace.hidden=!editor;listArea.hidden=editor;$('pvTabCreate').classList.toggle('active',editor);$('pvTabCreated').classList.toggle('active',!editor)};
  const filtered=()=>{const q=($('pvSearch').value||'').trim().toLocaleLowerCase('pt-BR'),f=$('pvFilter').value;return proposals.filter(r=>(!q||`${r.theme||''} ${r.thematic_axis||''} ${r.proposal_command||''}`.toLocaleLowerCase('pt-BR').includes(q))&&(f==='all'||f==='published'&&r.status==='Publicada'||f==='draft'&&r.status==='Rascunho'||f==='hidden'&&r.status==='Oculta'))};
  const draw=()=>{const rows=filtered();$('pvCount').textContent=`${rows.length} proposta${rows.length===1?'':'s'} encontrada${rows.length===1?'':'s'}.`;$('pvList').innerHTML=rows.map(r=>{const orgs=new Set((r.targets||[]).map(id=>classMap.get(String(id))?.orgId).filter(Boolean));const statusClass=r.status==='Publicada'?'ok':r.status==='Oculta'?'hidden':'warn';return `<article class="proposal-v3-card" data-id="${esc(r.id)}"><div class="proposal-v3-main"><div class="proposal-v3-title">${esc(r.theme||'Sem tema')}</div><div class="proposal-v3-chips">${r.thematic_axis?`<span class="proposal-v3-chip">${esc(r.thematic_axis)}</span>`:''}${orgs.size?`<span class="proposal-v3-chip">${orgs.size} instituição${orgs.size===1?'':'ões'}</span>`:''}</div>${r.proposal_command?`<p class="proposal-v3-command">${esc(r.proposal_command)}</p>`:''}<div class="proposal-v3-meta">${(r.targets||[]).length} turma${(r.targets||[]).length===1?'':'s'} · ${(r._motivators||[]).filter(m=>m.body).length} texto${(r._motivators||[]).filter(m=>m.body).length===1?'':'s'} motivador${(r._motivators||[]).filter(m=>m.body).length===1?'':'es'}</div></div><span class="proposal-v3-status ${statusClass}">${esc(r.status)}</span><div class="proposal-v3-actions"><button class="btn soft-btn" data-edit="${esc(r.id)}">Editar</button><button class="btn soft-btn" data-hide="${esc(r.id)}">${r.status==='Oculta'?'Reexibir':'Ocultar'}</button><button class="btn ghost danger" data-delete="${esc(r.id)}">Excluir</button></div></article>`}).join('')||'<div class="empty">Nenhuma proposta encontrada.</div>'};
  $('pvSearch').oninput=draw;$('pvFilter').onchange=draw;
  const showList=()=>{editing=null;workspace.innerHTML='';setView('list');draw()};

  const openEditor=record=>{
   editing=record||null;setView('editor');const original=record||{};let motRows=(original._motivators?.length?original._motivators:[{title:'',body:'',source_label:'',source_url:''}]).map(m=>({...m}));let selected=new Set((original.targets||[]).map(String)),recipientMode='org';
   workspace.innerHTML=`<div class="proposal-v3-editor"><button class="btn ghost" id="pvBack" type="button">Voltar às propostas</button><form id="pvForm"><section class="proposal-v3-section"><header><h2>1. Tema e orientação</h2><p>Defina o eixo antes do tema. Ele orienta a criação com IA.</p></header><label class="proposal-v3-axis">Eixo temático<select id="pvAxis" required><option value="">Selecione um eixo</option>${AXES.map(x=>`<option value="${esc(x)}" ${x===(original.thematic_axis||'')?'selected':''}>${esc(x)}</option>`).join('')}</select><small>Base para a criação com IA.</small></label><label class="field"><strong>Tema</strong><input id="pvTheme" required maxlength="250" value="${esc(original.theme||'')}"></label><section class="proposal-v3-ai"><div><h3>Criar com Inteligência</h3><p>Gere tema, comando e textos motivadores. Tudo continua editável antes da publicação.</p></div><div><button class="btn" id="pvGenerate" type="button">Criar com IA</button><small id="pvCredits" class="muted">Consultando saldo…</small></div></section><div><label><strong>Comando da proposta</strong></label><div class="demo-editor"><div class="item-actions" id="pvFormat"><button type="button" class="btn soft-btn" data-format="bold"><strong>Negrito</strong></button><button type="button" class="btn soft-btn" data-format="italic"><em>Itálico</em></button><button type="button" class="btn soft-btn" data-format="insertUnorderedList">Lista</button><button type="button" class="btn soft-btn" data-format="undo">Desfazer</button></div><div id="pvCommand" contenteditable="true" role="textbox" aria-multiline="true" data-placeholder="Escreva a orientação ao aluno..."></div></div></div><label class="field"><strong>Entenda o tema</strong><textarea id="pvUnderstand" placeholder="Delimite a problemática, o contexto e os limites do tema.">${esc(original.understand_prompt||'')}</textarea></label></section><section class="proposal-v3-section"><header><h2>2. Textos motivadores</h2><p>A fonte/autoria deve ser informada. O link é opcional.</p></header><div id="pvMotivators"></div><button class="btn soft-btn" id="pvAddMotivator" type="button">Adicionar texto motivador</button></section><section class="proposal-v3-section"><header><h2>3. Destinatários</h2><p>Selecione as instituições e as turmas que receberão esta proposta.</p></header><div id="pvRecipients"></div></section><div class="proposal-v3-footer"><button class="btn ghost" id="pvCancel" type="button">Cancelar</button><button class="btn soft-btn" id="pvDraft" type="button">Salvar rascunho</button></div></form><div id="pvPreview"></div></div>`;
   const editor=$('pvCommand');editor.innerHTML=proposalHtml(original.proposal_html||esc(original.proposal_command||''));let selection=null;
   const remember=()=>{const sel=window.getSelection();if(sel.rangeCount&&editor.contains(sel.anchorNode)&&editor.contains(sel.focusNode))selection=sel.getRangeAt(0).cloneRange()};editor.onkeyup=remember;editor.onmouseup=remember;editor.oninput=remember;editor.onblur=remember;editor.onpaste=e=>{e.preventDefault();document.execCommand('insertText',false,e.clipboardData.getData('text/plain'));remember()};
   $('pvFormat').onmousedown=e=>{if(e.target.closest('button'))e.preventDefault()};$('pvFormat').onclick=e=>{const b=e.target.closest('[data-format]');if(!b)return;editor.focus();if(selection){const sel=window.getSelection();sel.removeAllRanges();sel.addRange(selection)}document.execCommand(b.dataset.format,false,null);remember()};
   const renderMotivators=()=>{$('pvMotivators').innerHTML=motRows.map((m,i)=>`<fieldset class="proposal-v3-motivator" data-mot-row><legend>Texto motivador ${i+1}</legend><label>Título <span class="muted">(opcional)</span><input data-mot="title" value="${esc(m.title||'')}"></label><label>Texto<textarea data-mot="body">${esc(m.body||'')}</textarea></label><div class="proposal-v3-grid"><label>Fonte / autoria<input data-mot="source_label" value="${esc(m.source_label||'')}"></label><label>Link <span class="muted">(opcional)</span><input type="url" data-mot="source_url" value="${esc(m.source_url||'')}"></label></div>${motRows.length>1?`<button class="btn ghost danger" type="button" data-remove-mot="${i}">Remover texto</button>`:''}</fieldset>`).join('')};
   const readMotivators=()=>[...$('pvMotivators').querySelectorAll('[data-mot-row]')].map((row,i)=>({...motRows[i],...Object.fromEntries([...row.querySelectorAll('[data-mot]')].map(el=>[el.dataset.mot,el.value.trim()]))}));renderMotivators();$('pvAddMotivator').onclick=()=>{motRows=[...readMotivators(),{title:'',body:'',source_label:'',source_url:''}];renderMotivators()};$('pvMotivators').onclick=e=>{const b=e.target.closest('[data-remove-mot]');if(!b)return;motRows=readMotivators().filter((_,i)=>i!==Number(b.dataset.removeMot));renderMotivators()};
   const classes=allClasses(institutions);const cmap=new Map(classes.map(c=>[String(c.id),c]));
   const renderRecipients=()=>{const list=recipientMode==='class'?`<div class="recipient-v3-flat">${classes.map(c=>`<label class="recipient-v3-row"><input class="recipient-v3-check recipient-v3-class-check" type="checkbox" data-class="${esc(c.id)}" ${selected.has(String(c.id))?'checked':''}><span>${esc(c.name)}</span><span class="recipient-v3-meta">${esc(c.orgName)}</span></label>`).join('')}</div>`:institutions.map((o,i)=>`<section class="recipient-v3-org" data-org="${esc(o.id)}" data-collapsed="${i<2?'0':'1'}"><div class="recipient-v3-head"><input class="recipient-v3-check" type="checkbox" data-org-check="${esc(o.id)}"><div class="recipient-v3-title"><strong>${esc(o.name)}</strong><span>${o.classes.length} turma${o.classes.length===1?'':'s'}</span></div><button type="button" class="recipient-v3-toggle" data-toggle>⌃</button></div><div class="recipient-v3-body">${o.classes.map(c=>`<label class="recipient-v3-row"><input class="recipient-v3-check recipient-v3-class-check" type="checkbox" data-class="${esc(c.id)}" ${selected.has(String(c.id))?'checked':''}><span>${esc(c.name)}</span><span></span></label>`).join('')||'<div class="muted">Nenhuma turma disponível.</div>'}</div></section>`).join('');$('pvRecipients').innerHTML=`<div class="recipient-v3"><div class="recipient-v3-tabs"><button type="button" class="recipient-v3-tab ${recipientMode==='org'?'active':''}" data-mode="org">Por instituição</button><button type="button" class="recipient-v3-tab ${recipientMode==='class'?'active':''}" data-mode="class">Por turma</button></div><label class="recipient-v3-all"><input class="recipient-v3-check" type="checkbox" data-all><strong>Selecionar todas as instituições e turmas</strong><span>${institutions.length} instituições · ${classes.length} turmas disponíveis</span></label><div data-rec-list>${list}</div><div class="recipient-v3-bottom"><div class="recipient-v3-selected"><span>Selecionadas:</span><strong>${selected.size} turma${selected.size===1?'':'s'} selecionada${selected.size===1?'':'s'}</strong></div><button type="button" class="btn primary" data-continue ${selected.size?'':'disabled'}>Continuar →</button></div></div>`;const root=$('pvRecipients');const all=root.querySelector('[data-all]');all.checked=classes.length>0&&selected.size===classes.length;all.indeterminate=selected.size>0&&selected.size<classes.length;institutions.forEach(o=>{const b=root.querySelector(`[data-org-check="${CSS.escape(String(o.id))}"]`);if(!b)return;const n=o.classes.filter(c=>selected.has(String(c.id))).length;b.checked=o.classes.length>0&&n===o.classes.length;b.indeterminate=n>0&&n<o.classes.length})};renderRecipients();
   $('pvRecipients').onclick=e=>{const mode=e.target.closest('[data-mode]');if(mode){recipientMode=mode.dataset.mode;renderRecipients();return}const t=e.target.closest('[data-toggle]');if(t){const card=t.closest('[data-org]');card.dataset.collapsed=card.dataset.collapsed==='1'?'0':'1';return}if(e.target.closest('[data-continue]'))showPreview()};$('pvRecipients').onchange=e=>{if(e.target.matches('[data-all]')){selected.clear();if(e.target.checked)classes.forEach(c=>selected.add(String(c.id)));renderRecipients();return}if(e.target.matches('[data-org-check]')){const o=institutions.find(x=>String(x.id)===e.target.dataset.orgCheck);o?.classes.forEach(c=>e.target.checked?selected.add(String(c.id)):selected.delete(String(c.id)));renderRecipients();return}if(e.target.matches('[data-class]')){const id=String(e.target.dataset.class);e.target.checked?selected.add(id):selected.delete(id);renderRecipients()}};
   const refreshCredits=async()=>{try{const c=await edge(API.proposal,{action:'credits'});if($('pvCredits'))$('pvCredits').textContent=`Saldo: ${c.balance} crédito(s)`}catch{if($('pvCredits'))$('pvCredits').textContent='Saldo indisponível'}};refreshCredits();$('pvAxis').onchange=()=>{generationId=null};
   $('pvGenerate').onclick=async()=>{const axis=$('pvAxis').value;if(!axis)return actionMessage('Selecione o eixo temático.','Atenção');if(!await appConfirm('Usar 1 crédito para criar tema e textos motivadores com pesquisa de fontes? O conteúdo atual será substituído. Em caso de falha, o crédito será devolvido.'))return;const stop=loader();try{const key='versao-proposal-request:'+S.session.user.id+':'+axis;try{generationId=generationId||localStorage.getItem(key)}catch{}generationId=generationId||crypto.randomUUID();try{localStorage.setItem(key,generationId)}catch{}const result=await edge(API.proposal,{action:'generate',thematic_axis:axis,request_id:generationId});$('pvTheme').value=result.proposal.theme;editor.textContent=result.proposal.proposal_command;$('pvUnderstand').value=result.proposal.understand_prompt||'';motRows=result.proposal.motivators||[];renderMotivators();try{localStorage.removeItem(key)}catch{}generationId=null;actionMessage('Proposta criada. Revise antes de publicar.')}catch(error){if(error.refunded)generationId=null;actionMessage(error.message||'Não foi possível criar a proposta.','Atenção')}finally{stop();refreshCredits()}};
   const collectMot=()=>readMotivators().filter(m=>m.body);const validate=publish=>{if(!$('pvForm').reportValidity())return null;if(!editor.innerText.trim()){actionMessage('Preencha o comando da proposta.','Atenção');return null}const motivators=collectMot();if(!motivators.length){actionMessage('Inclua ao menos um texto motivador.','Atenção');return null}if(publish&&motivators.some(m=>!m.source_label)){actionMessage('Informe a fonte/autoria de cada texto motivador.','Atenção');return null}if(publish&&!selected.size){actionMessage('Selecione pelo menos uma turma.','Atenção');return null}return motivators};
   async function save(publish){if(writing)return;const motivators=validate(publish);if(!motivators)return;if(publish&&!await appConfirm(`Publicar esta proposta para ${selected.size} turma(s)?`))return;writing=true;try{const ids=[...selected],orgIds=[...new Set(ids.map(id=>cmap.get(String(id))?.orgId).filter(Boolean))],anchorOrg=orgIds[0]||institutions[0]?.id||null,anchorIds=ids.filter(id=>String(cmap.get(String(id))?.orgId)===String(anchorOrg));const payload={action:'save',round_id:editing?.id||undefined,theme:$('pvTheme').value.trim(),thematic_axis:$('pvAxis').value,proposal_command:editor.innerText.trim(),proposal_html:proposalHtml(editor.innerHTML),publish,organization_id:anchorOrg,due_date:editing?.due_date||null,understand_prompt:$('pvUnderstand').value.trim(),class_ids:orgIds.length>1?anchorIds:ids,motivators};const result=await edge(API.proposal,payload);const roundId=String(editing?.id||result?.proposal?.id||result?.round_id||'');if(orgIds.length>1){if(!roundId)throw Error('A proposta foi salva, mas não foi possível confirmar os destinatários.');await exactTargets(roundId,ids)}actionMessage(publish?'A proposta foi publicada para as turmas selecionadas.':'O rascunho foi salvo.',publish?'Proposta publicada':'Proposta salva');await renderDemoProposalsV3(navigation)}catch(error){actionMessage(error.message||'Não foi possível salvar a proposta.','Atenção')}finally{writing=false}};
   function showPreview(){const motivators=validate(true);if(!motivators)return;const orgs=new Set([...selected].map(id=>cmap.get(String(id))?.orgId).filter(Boolean));$('pvForm').hidden=true;$('pvPreview').innerHTML=`<section class="proposal-v3-preview"><div><h2>Prévia da proposta</h2><p class="muted">Revise antes de publicar.</p></div><article class="proposal-v3-preview-card"><div class="proposal-v3-preview-theme">${esc($('pvTheme').value.trim())}</div><div class="proposal-v3-chips"><span class="proposal-v3-chip">${esc($('pvAxis').value)}</span><span class="proposal-v3-chip">${selected.size} turma(s) · ${orgs.size} instituição(ões)</span></div><div><strong>Comando da proposta</strong><p style="white-space:pre-wrap;color:#475467">${esc(editor.innerText.trim())}</p></div>${$('pvUnderstand').value.trim()?`<div class="proposal-v3-understand"><strong>O que o tema está pedindo</strong><br>${esc($('pvUnderstand').value.trim())}</div>`:''}<div><strong>Textos motivadores</strong><div class="proposal-v3-mot-list">${motivators.map((m,i)=>`<div class="proposal-v3-mot"><b>${esc(m.title||`Texto motivador ${i+1}`)}</b><span>${esc(m.source_label||'Fonte informada')}</span></div>`).join('')}</div></div><div class="proposal-v3-dest"><b>Destinatários:</b> ${selected.size} turma(s) em ${orgs.size} instituição(ões)</div></article><div class="proposal-v3-preview-actions"><button class="btn ghost" id="pvPreviewBack" type="button">← Voltar e editar</button><button class="btn soft-btn" id="pvPreviewDraft" type="button">Salvar como rascunho</button><button class="btn primary" id="pvPreviewPublish" type="button">Publicar proposta</button></div></section>`;$('pvPreviewBack').onclick=()=>{$('pvPreview').innerHTML='';$('pvForm').hidden=false};$('pvPreviewDraft').onclick=()=>save(false);$('pvPreviewPublish').onclick=()=>save(true);$('pvPreview').scrollIntoView({block:'start',behavior:'smooth'})}
   $('pvBack').onclick=showList;$('pvCancel').onclick=showList;$('pvDraft').onclick=()=>save(false);$('pvForm').onsubmit=e=>e.preventDefault();
  };
  $('pvTabCreate').onclick=()=>openEditor(null);$('pvTabCreated').onclick=showList;
  $('pvList').onclick=async e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.edit||b.dataset.hide||b.dataset.delete,r=proposals.find(x=>String(x.id)===String(id));if(!r)return;if(b.dataset.edit){openEditor(r);return}const ids=r._ids?.length?r._ids:[r.id];if(b.dataset.delete&&!await appConfirm(`Excluir esta proposta${ids.length>1?' de todas as instituições':''}? Propostas com redações vinculadas não podem ser excluídas.`))return;b.disabled=true;try{if(b.dataset.hide){const next=r.status==='Oculta'?'published':'closed';await Promise.all(ids.map(x=>edge(API.proposal,{action:'update_status',round_id:x,status:next})))}else await Promise.all(ids.map(x=>edge(API.proposal,{action:'delete',round_id:x})));await renderDemoProposalsV3(navigation)}catch(error){actionMessage(error.message||'Não foi possível atualizar a proposta.','Atenção')}finally{b.disabled=false}};
  draw();setView('list');const home=S.homeProposal;S.homeProposal=null;if(home?.intent==='create')openEditor(null);else if(home?.target){const r=proposals.find(x=>String(x.id)===String(home.target));if(r)openEditor(r)}
 }
 window.renderDemoProposals=renderDemoProposalsV3;
})();