'use strict';
const importFields=[['nameColumn','Nome'],['registrationColumn','Matrícula'],['emailColumn','E-mail'],['schoolColumn','Escola'],['classColumn','Turma']];
const importNormalize=v=>String(v||'').trim().replace(/\s+/g,' ').toLocaleLowerCase('pt-BR');
function importMatches(row,candidates){return candidates.filter(s=>importNormalize(s.full_name)===importNormalize(row.name)||row.email&&importNormalize(s.email)===importNormalize(row.email)||row.registration&&s.registration===row.registration);}
function importCall(action,data={}){return edge('teacher-import-api',{action,...data});}
async function renderTeacherImport(navigation,options={}){
 if(S.profile?.role!=='teacher')throw Error('Esta área é destinada ao professor.');
 const actor=S.profile.id||S.session.user.id,current=()=>navigationCurrent(navigation)&&actor===(S.profile?.id||S.session?.user?.id);
 const initial=S.importEntry;S.importEntry=null;
 const data=await catalogCall('organizations');if(!current())return;
 const schools=data.organizations.filter(s=>s.is_active!==false),classCache=new Map();
 const hint=S.catalogSelection;S.catalogSelection=null;S.organizationIntent=null;
 const d={step:1,text:'',table:[],mapping:null,sheets:[],sheet:0,source:'',rows:[],groups:[],candidates:[],choices:[],page:0,busy:false,reading:false,version:0,aiRequest:'',aiSource:'',aiUsed:false,paidResult:null,manual:false};
 const message=text=>{if(current()&&$('importStatus'))$('importStatus').textContent=text;};
 const first=(S.profile.full_name||'Professor').trim().split(/\s+/)[0];
 function shell(){
  if(!current())return;
  if(d.lastStep!==d.step){window.scrollTo({top:0,behavior:'instant'});d.lastStep=d.step;}
  $('view').innerHTML=`<section class="import-page"><header class="import-welcome"><p class="eyebrow">${options.home?'Primeiros passos':'Prepare sua turma'}</p><h1>${options.home?'Olá, '+esc(first)+'.':'Importar alunos'}</h1><p>Vamos preparar ${options.home?'sua primeira':'a próxima'} turma?</p></header><section class="import-card"><div class="import-card-head"><span class="import-ai-badge">Assistência de IA</span><h2>Seus alunos são o primeiro passo</h2><p>Envie sua lista. A VERSÃO ajuda a organizar os dados para você conferir.</p></div><div class="import-body"><ol class="import-steps" aria-label="Etapas da importação">${[['Enviar lista','Lista'],['Escola e turma','Turma'],['Conferir e começar','Conferir']].map(([label,short],i)=>`<li ${d.step===i+1?'aria-current="step"':''}><span>${d.step>i+1?'✓':i+1}</span><b class="long-label">${label}</b><b class="short-label">${short}</b></li>`).join('')}</ol><div id="importStage"></div><p id="importStatus" class="import-status" role="status" aria-live="polite"></p></div></section><p class="import-reassurance">Depois de preparar a turma, você poderá criar sua primeira proposta.</p></section>`;
 }
 async function run(fn,progress='Conferindo a lista…'){
  if(d.busy||d.reading)return;d.busy=true;
  $('importStage')?.querySelectorAll('button,input,textarea').forEach(e=>e.disabled=true);message(progress);
  try{await fn();}catch(e){message(e.message||'Não foi possível concluir. Sua lista continua disponível.');}
  finally{d.busy=false;if(current())$('importStage')?.querySelectorAll('button,input,textarea').forEach(e=>e.disabled=e.dataset.keepDisabled==='true');}
 }
 function setTable(table,source){d.table=table;d.source=source;d.rows=[];d.mapping=null;d.aiUsed=false;d.paidResult=null;try{d.mapping=RosterReader.infer(table);}catch{}}
 function drawInput(){
  d.step=1;shell();
  $('importStage').innerHTML=`<div class="import-drop" id="importDrop"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 3h8l4 4v14H6zM14 3v5h5M12 17V10m-3 3 3-3 3 3"/></svg><h3>Traga a lista que você já usa</h3><p>Excel (.xlsx ou .xls) e CSV · até 500 alunos por lote</p><input type="file" id="importFile" accept=".xlsx,.xls,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel,text/csv" hidden><button type="button" class="btn primary" id="importPick">Selecionar lista de alunos</button><br><button type="button" class="import-link" id="importPaste">Ou cole sua lista</button></div><details id="importPastePanel" ${d.text||d.manual?'open':'hidden'}><summary>${d.manual?'Adicionar alunos manualmente':'Colar ou digitar uma lista'}</summary><label class="field"><small>Um nome por linha ou células copiadas da planilha</small><textarea id="importText" rows="6" placeholder="Nome&#9;Matrícula&#9;Turma&#10;Ana Costa&#9;0012&#9;1º A"></textarea></label><button class="btn ghost" type="button" id="importReadText">Conferir estes dados</button></details><div id="importSource"></div><p class="import-reassurance">✓ Você revisa tudo antes de salvar.</p><div class="import-alternatives"><a href="/modelos/modelo-alunos.xlsx" download>Baixar planilha modelo</a><button class="import-link" type="button" id="importManual">Adicionar alunos manualmente</button></div><details><summary>O que minha lista precisa ter?</summary><p class="import-note">Somente o nome é obrigatório. Matrícula, e-mail, escola e turma são opcionais. Mantenha um aluno por linha. Você pode informar a escola e a turma no próximo passo. Excel: até 5 MB; CSV e texto: até 250 KB. Importe uma aba por vez.</p></details>`;
  $('importText').value=d.text;
  $('importPick').onclick=()=>{if(!d.busy)$('importFile').click();};
  $('importPaste').onclick=()=>{$('importPastePanel').hidden=false;$('importPastePanel').open=true;$('importText').focus();};
  $('importManual').onclick=()=>{d.manual=true;$('importPastePanel').hidden=false;$('importPastePanel').open=true;$('importText').focus();};
  $('importText').oninput=()=>{d.text=$('importText').value;d.table=[];d.mapping=null;d.rows=[];d.sheets=[];d.paidResult=null;d.aiUsed=false;$('importSource').innerHTML='';};
  $('importReadText').onclick=()=>{try{d.text=$('importText').value;setTable(RosterReader.textTable(d.text),'Lista colada');drawSource();message('Confira as colunas reconhecidas.');}catch(e){message(e.message);}};
  $('importFile').onchange=()=>readFile($('importFile').files[0]);
  const drop=$('importDrop');drop.ondragover=e=>{e.preventDefault();drop.classList.add('is-dragging');};drop.ondragleave=()=>drop.classList.remove('is-dragging');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('is-dragging');readFile(e.dataTransfer.files[0]);};
  if(d.table.length)drawSource();
 }
 async function readFile(file){
  if(!file||d.busy||d.reading)return;
  const version=++d.version;d.reading=true;message('Lendo a lista…');$('importStage').querySelectorAll('button,input,textarea').forEach(e=>e.disabled=true);
  try{
   let sheets;
   if(/\.csv$/i.test(file.name)){if(file.size>250000)throw Error('Divida o CSV em arquivos de até 250 KB.');sheets=[{name:file.name,rows:RosterReader.textTable(await file.text())}];}
   else if(/\.(xlsx|xls)$/i.test(file.name))sheets=await RosterReader.workbookFile(file);
   else throw Error('Envie Excel (.xlsx ou .xls), CSV ou cole os dados da lista.');
   if(!current()||version!==d.version)return;
   d.sheets=sheets;d.sheet=Math.max(0,sheets.findIndex(s=>/^alunos$/i.test(s.name)));d.text='';d.source=file.name;selectSheet(d.sheet);drawInput();message('Arquivo carregado. Confira a aba e escolha como organizar.');
  }catch(e){message(e.message);}finally{d.reading=false;if(current())$('importStage')?.querySelectorAll('button,input,textarea').forEach(e=>e.disabled=e.dataset.keepDisabled==='true');}
 }
 function selectSheet(index){const sheet=d.sheets[index];if(sheet.error)throw Error(sheet.error);d.sheet=index;setTable(sheet.rows,d.source);}
 function drawSource(){
  const width=Math.max(0,...d.table.map(r=>r.length)),mapping=d.mapping||{nameColumn:0,emailColumn:-1,registrationColumn:-1,schoolColumn:-1,classColumn:-1,startRow:0};d.mapping=mapping;
  $('importSource').innerHTML=`<div class="import-source"><strong>${esc(d.source)}</strong><p>${d.table.filter(r=>r.some(v=>String(v).trim())).length} linhas no arquivo${d.sheets.length?' · Aba: '+esc(d.sheets[d.sheet].name):''}</p>${d.sheets.length>1?`<div class="import-options" aria-label="Escolher aba">${d.sheets.map((s,i)=>`<button class="btn ghost" type="button" data-import-sheet="${i}" aria-pressed="${i===d.sheet}">${esc(s.name)}</button>`).join('')}</div>`:''}</div><div class="import-table-wrap"><table class="import-table"><caption>Prévia do arquivo · primeiras 5 linhas</caption><thead><tr><th>Linha</th>${Array.from({length:width},(_,i)=>`<th>Coluna ${i+1}</th>`).join('')}</tr></thead><tbody>${d.table.slice(0,5).map((r,i)=>`<tr><td>${i+1}</td>${Array.from({length:width},(_,c)=>`<td>${esc(r[c]||'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="import-note">${d.aiUsed?'A IA sugeriu estas colunas. Confira antes de continuar.':'A IA reconhece as colunas e ajuda a separar as turmas. O cadastro só acontece após sua confirmação.'}</p><div class="item-actions"><button class="btn primary" type="button" id="importAI">${d.paidResult?'Rever organização da IA':'Organizar com IA · 1 crédito'}</button><button class="btn ghost" type="button" id="importContinue">${d.aiUsed?'Continuar para escola e turma':'Conferir sem IA · gratuito'}</button></div><p class="import-note">1 crédito por análise concluída. Falhas técnicas devolvem o crédito. Uma amostra das primeiras linhas será enviada à IA para reconhecer as colunas.</p><details id="importMapping" ${d.aiUsed?'open':''}><summary>Conferir ou ajustar as colunas</summary><div class="import-mapping">${importFields.map(([key,label])=>`<fieldset><legend>${label}</legend>${(key==='nameColumn'?[]:[-1]).concat(Array.from({length:width},(_,i)=>i)).map(i=>`<label><input type="radio" name="map-${key}" data-import-map="${key}" value="${i}" ${(mapping[key]??-1)===i?'checked':''}>${i<0?'Não está na lista':`Coluna ${i+1} · ${esc(String(d.table[mapping.headerRow>=0?mapping.headerRow:0]?.[i]||'').slice(0,45))}`}</label>`).join('')}</fieldset>`).join('')}</div><label class="field"><small>Primeira linha de alunos (sem o cabeçalho)</small><input id="importStartRow" type="number" min="1" max="${d.table.length}" value="${mapping.startRow+1}"></label><p class="import-note">Colunas sem associação não serão cadastradas. Matrículas permanecem separadas dos nomes.</p></details>`;
  $('importSource').querySelectorAll('[data-import-sheet]').forEach(b=>b.onclick=()=>{if(d.busy)return;try{selectSheet(Number(b.dataset.importSheet));drawSource();message('');}catch(e){message(e.message);}});
  $('importSource').querySelectorAll('[data-import-map]').forEach(e=>e.onchange=()=>{d.mapping[e.dataset.importMap]=Number(e.value);d.rows=[];});
  $('importStartRow').oninput=()=>{d.mapping.startRow=Number($('importStartRow').value)-1;d.rows=[];};
  const editor=document.createElement('details');editor.innerHTML='<summary>Corrigir dados da lista aqui</summary><div id="importCellEditor"></div>';$('importSource').append(editor);
  let editPage=0;
  function drawCells(){const offset=editPage*10,rows=d.table.slice(offset,offset+10);$('importCellEditor').innerHTML=`<div class="import-table-wrap"><table class="import-table"><thead><tr><th>Linha</th>${Array.from({length:width},(_,i)=>`<th>Coluna ${i+1}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${offset+i+1}</td>${Array.from({length:width},(_,c)=>`<td><input aria-label="Linha ${offset+i+1}, coluna ${c+1}" data-cell-row="${offset+i}" data-cell-col="${c}" value="${esc(r[c]||'')}" maxlength="254"></td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="import-pagination"><button class="btn ghost" type="button" id="importCellPrev" ${editPage===0?'disabled data-keep-disabled="true"':''}>Anterior</button><span>${offset+1}–${Math.min(offset+10,d.table.length)} de ${d.table.length}</span><button class="btn ghost" type="button" id="importCellNext" ${offset+10>=d.table.length?'disabled data-keep-disabled="true"':''}>Próximas linhas</button></div>`;
   $('importCellEditor').querySelectorAll('[data-cell-row]').forEach(el=>el.oninput=()=>{d.table[Number(el.dataset.cellRow)][Number(el.dataset.cellCol)]=el.value;d.rows=[];d.paidResult=null;});
   $('importCellPrev').onclick=()=>{if(editPage){editPage--;drawCells();}};$('importCellNext').onclick=()=>{if(offset+10<d.table.length){editPage++;drawCells();}};
  }drawCells();
  $('importAI').onclick=()=>run(async()=>{
   const sample=d.table.slice(0,20).map(r=>r.map(v=>String(v??'').slice(0,120))),source=JSON.stringify(sample);
   if(source!==d.aiSource){d.aiSource=source;d.aiRequest=crypto.randomUUID();}
   const result=d.paidResult||await importCall('organize',{request_id:d.aiRequest,sample});
   if(!current())return;d.mapping={...result.mapping};d.paidResult=result;d.aiUsed=true;d.rows=[];drawSource();message(result.reused?'Organização recuperada sem nova cobrança. Confira as colunas.':'Colunas organizadas. Confira a prévia e continue.');
  },'A IA está reconhecendo as colunas da lista…');
  $('importContinue').onclick=()=>run(async()=>{d.rows=RosterReader.map(d.table,d.mapping);buildGroups();await loadSuggestedClasses();if(current()){drawDestination();message('Confira onde cada grupo será cadastrado. Nada foi salvo ainda.');}});
 }
 function buildGroups(){
  const groups=new Map();
  d.rows.forEach((row,index)=>{const key=JSON.stringify([importNormalize(row.school),importNormalize(row.className)]);if(!groups.has(key)){const school=schools.find(s=>importNormalize(s.name)===importNormalize(row.school))||(!row.school?schools.find(s=>s.id===hint?.organization_id):null);groups.set(key,{key:String(groups.size),schoolName:row.school||school?.name||'',organization_id:school?.id||'',className:row.className||'',class_id:'',year:new Date().getFullYear(),indices:[],classes:[]});}groups.get(key).indices.push(index);});
  d.groups=[...groups.values()];if(d.groups.length>20)throw Error('Foram encontrados mais de 20 grupos. Confira a coluna de turma ou divida a lista.');
 }
 async function getClasses(oid){if(!oid)return[];if(!classCache.has(oid)){const result=await catalogCall('base',{organization_id:oid});classCache.set(oid,result.classes.filter(c=>c.is_active!==false));}return classCache.get(oid);}
 async function loadSuggestedClasses(){for(const g of d.groups){g.classes=await getClasses(g.organization_id);const found=g.classes.find(c=>importNormalize(c.name)===importNormalize(g.className)&&Number(c.year)===g.year)||(!g.className?g.classes.find(c=>c.id===hint?.class_id):null);if(found){g.class_id=found.id;g.className=found.name;g.year=Number(found.year);}}}
 function drawDestination(){
  d.step=2;shell();
  $('importStage').innerHTML=`<h2>Onde seus alunos vão estudar?</h2><p class="import-note">${d.rows.length} alunos em ${d.groups.length} grupo${d.groups.length===1?'':'s'}. Escolha cadastros existentes ou informe os nomes para criar. Tudo será salvo na confirmação final.</p>${d.groups.map((g,i)=>`<section class="import-group"><h3>${esc(g.className||'Grupo '+(i+1))} · ${g.indices.length} alunos</h3><div class="import-options" aria-label="Escolas disponíveis">${schools.map(s=>`<button class="btn ghost" type="button" data-import-school="${esc(s.id)}" data-group="${i}" aria-pressed="${s.id===g.organization_id}">${esc(s.name)}</button>`).join('')}<button class="btn ghost" type="button" data-import-school="" data-group="${i}" aria-pressed="${!g.organization_id}">Nova escola</button></div><div class="import-dest-fields"><label class="field"><small>Nome da escola</small><input data-dest="schoolName" data-group="${i}" value="${esc(g.schoolName)}" maxlength="160" ${g.organization_id?'readonly':''}></label><label class="field"><small>Nome da turma</small><input data-dest="className" data-group="${i}" value="${esc(g.className)}" maxlength="80" placeholder="Ex.: 1º A"></label><label class="field"><small>Ano</small><input data-dest="year" data-group="${i}" type="number" min="2000" max="2100" value="${g.year}"></label></div>${g.classes.length?`<div class="import-options" aria-label="Turmas disponíveis">${g.classes.map(c=>`<button class="btn ghost" type="button" data-import-class="${esc(c.id)}" data-group="${i}" aria-pressed="${g.class_id===c.id}">${esc(c.name)} · ${c.year}</button>`).join('')}</div>`:''}<p class="import-note">${g.organization_id?'Escola selecionada':'A escola será criada ao confirmar'}${g.class_id?' · Turma selecionada':' · A turma será criada ou vinculada pelo nome e ano'}</p></section>`).join('')}<div class="item-actions"><button class="btn ghost" type="button" id="importBack">Voltar à lista</button><button class="btn primary" type="button" id="importReview">Conferir alunos</button></div>`;
  $('importStage').querySelectorAll('[data-dest]').forEach(el=>el.oninput=()=>{const g=d.groups[Number(el.dataset.group)];g[el.dataset.dest]=el.dataset.dest==='year'?Number(el.value):el.value;if(['className','year'].includes(el.dataset.dest))g.class_id='';});
  $('importStage').querySelectorAll('[data-import-school]').forEach(b=>b.onclick=()=>run(async()=>{const g=d.groups[Number(b.dataset.group)],school=schools.find(s=>s.id===b.dataset.importSchool);g.organization_id=school?.id||'';g.schoolName=school?.name||'';g.class_id='';g.classes=await getClasses(g.organization_id);if(current())drawDestination();},'Carregando turmas…'));
  $('importStage').querySelectorAll('[data-import-class]').forEach(b=>b.onclick=()=>{if(d.busy)return;const g=d.groups[Number(b.dataset.group)],c=g.classes.find(c=>c.id===b.dataset.importClass);g.class_id=c.id;g.className=c.name;g.year=Number(c.year);drawDestination();});
  $('importBack').onclick=drawInput;
  $('importReview').onclick=()=>run(async()=>{if(d.groups.some(g=>g.schoolName.trim().length<2||!g.className.trim()||!Number.isInteger(g.year)||g.year<2000||g.year>2100))throw Error('Informe escola, turma e um ano entre 2000 e 2100 para cada grupo.');const result=await importCall('review',{groups:payloadGroups(false)});if(!current())return;d.candidates=result.groups;d.choices=d.rows.map((row,i)=>matches(i).length||repeated(i)?'':'new');d.page=0;drawReview();});
 }
 const groupFor=i=>d.groups.find(g=>g.indices.includes(i));
 function matches(i){return importMatches(d.rows[i],d.candidates.find(c=>c.key===groupFor(i).key)?.candidates||[]);}
 function repeated(i){const row=d.rows[i],g=groupFor(i);return g.indices.some(j=>j<i&&(importNormalize(d.rows[j].name)===importNormalize(row.name)||row.email&&d.rows[j].email===row.email||row.registration&&d.rows[j].registration===row.registration));}
 function payloadGroups(withChoices){return d.groups.map(g=>({key:g.key,organization_id:g.organization_id||null,school_name:g.schoolName.trim(),class_id:g.class_id||null,class_name:g.className.trim(),year:g.year,rows:g.indices.map(i=>{const r=d.rows[i],choice=d.choices[i];return{name:r.name,email:r.email,registration:r.registration,...(withChoices?{choice:['new','skip'].includes(choice)?choice:'existing',student_id:['new','skip'].includes(choice)?null:choice,homonym:choice==='new'&&(matches(i).length>0||repeated(i))}:{})};})}));}
 function drawReview(){
  d.step=3;shell();const start=d.page*10,pending=d.choices.filter(c=>!c).length;
  $('importStage').innerHTML=`<h2>Confira e comece</h2><p class="import-note">${d.rows.length} alunos encontrados · ${d.groups.length} turma${d.groups.length===1?'':'s'} · <strong>${pending} precisam de atenção</strong></p><div>${d.rows.slice(start,start+10).map((row,offset)=>{const i=start+offset,g=groupFor(i),candidates=matches(i),conflict=candidates.length||repeated(i);return `<article class="import-review-row ${conflict?'is-warning':''}"><div class="import-row-top"><div><strong>${esc(row.name)}</strong><small>${esc(g.schoolName)} · ${esc(g.className)}</small><small>Matrícula: ${esc(row.registration||'não informada')} · ${esc(row.email||'sem e-mail')}</small></div><label><input type="checkbox" data-import-skip="${i}" ${d.choices[i]==='skip'?'checked':''}>Ignorar linha</label></div>${conflict?`<fieldset class="import-conflict"><legend>Possível duplicidade. Escolha o cadastro correto.</legend>${candidates.map(s=>`<label><input type="radio" name="choice-${i}" data-import-choice="${i}" value="${esc(s.id)}" ${d.choices[i]===s.id?'checked':''}>Usar ${esc(s.full_name)}${s.registration?' · '+esc(s.registration):''}${s.enrolled?' · já nesta turma':''}</label>`).join('')}<label><input type="radio" name="choice-${i}" data-import-choice="${i}" value="new" ${d.choices[i]==='new'?'checked':''}>Cadastrar outra pessoa com este nome</label></fieldset>`:''}</article>`;}).join('')}</div><div class="import-pagination"><button type="button" class="btn ghost" id="importPrev" ${d.page===0?'disabled data-keep-disabled="true"':''}>Anterior</button><span>${start+1}–${Math.min(start+10,d.rows.length)} de ${d.rows.length}</span><button type="button" class="btn ghost" id="importNextPage" ${start+10>=d.rows.length?'disabled data-keep-disabled="true"':''}>Próximos 10</button></div><div class="item-actions"><button class="btn ghost" type="button" id="importEdit">Voltar e ajustar</button>${pending?'<button class="btn ghost" type="button" id="importFirstIssue">Ver pendência</button>':''}<button class="btn primary" type="button" id="importCommit">Confirmar e preparar turma${d.groups.length>1?'s':''}</button></div><p class="import-note">Esta confirmação cadastra os alunos. Nenhum crédito adicional é consumido.</p>`;
  $('importPrev').onclick=()=>{if(d.page>0){d.page--;drawReview();}};$('importNextPage').onclick=()=>{if(start+10<d.rows.length){d.page++;drawReview();}};
  $('importEdit').onclick=drawDestination;if($('importFirstIssue'))$('importFirstIssue').onclick=()=>{d.page=Math.floor(d.choices.findIndex(c=>!c)/10);drawReview();};
  $('importStage').querySelectorAll('[data-import-choice]').forEach(e=>e.onchange=()=>{d.choices[Number(e.dataset.importChoice)]=e.value;drawReview();});
  $('importStage').querySelectorAll('[data-import-skip]').forEach(e=>e.onchange=()=>{const i=Number(e.dataset.importSkip);d.choices[i]=e.checked?'skip':matches(i).length||repeated(i)?'':'new';drawReview();});
  $('importCommit').onclick=()=>run(async()=>{if(d.choices.some(c=>!c))throw Error('Resolva as possíveis duplicidades antes de confirmar.');if(d.choices.every(c=>c==='skip'))throw Error('Selecione ao menos um aluno para cadastrar.');const groups=payloadGroups(true),source=JSON.stringify(groups);if(d.commitSource!==source){d.commitSource=source;d.commitId=crypto.randomUUID();}const saved=await importCall('commit',{request_id:d.commitId,groups});if(!current())return;S.cache={};S.student=null;drawDone(saved);},'Preparando suas turmas…');
 }
 function drawDone(saved){
  window.scrollTo({top:0,behavior:'instant'});
  shell();$('importStage').innerHTML=`<div class="import-success"><span class="import-success-mark">✓</span><h2>Sua${saved.groups.length>1?'s turmas estão prontas':' turma está pronta'}!</h2><p>${saved.processed} alunos vinculados. Agora você pode criar a primeira proposta.</p><button class="btn primary" type="button" id="importProposal">Criar primeira proposta</button></div>${saved.groups.map((g,i)=>`<div class="import-group"><h3>${esc(g.school_name)} · ${esc(g.class_name)}</h3><p class="import-note">${g.processed} alunos · cada aluno acessa com o código da turma e seu PIN.</p><button class="btn ghost" type="button" data-import-students="${i}">Ver alunos e PINs</button></div>`).join('')}<button class="import-link" type="button" id="importAnother">Importar outra lista</button>`;
  $('importProposal').onclick=()=>{S.homeProposal={intent:'create'};navigate('proposals');};
  $('importStage').querySelectorAll('[data-import-students]').forEach(b=>b.onclick=()=>{const g=saved.groups[Number(b.dataset.importStudents)];S.catalogSelection={organization_id:g.organization_id,class_id:g.class_id};navigate('teacher-students');});
  $('importAnother').onclick=()=>navigate('teacher-import');
 }
 drawInput();if(initial?.file)await readFile(initial.file);if(initial?.manual){d.manual=true;$('importPastePanel').hidden=false;$('importPastePanel').open=true;$('importText').focus();}
}
