'use strict';
function ensureTeacherHomeStyle(){
 if(document.getElementById('teacherHomeV2Style'))return;
 const style=document.createElement('style');style.id='teacherHomeV2Style';style.textContent=`
 .th2{max-width:980px;margin:0 auto;display:grid;gap:22px}.th2-head{display:flex;align-items:flex-start;justify-content:space-between;gap:18px}.th2-head h1{font-size:32px;line-height:1.05;margin:0 0 8px}.th2-head p{margin:0;color:#67636a;line-height:1.5}.th2-refresh{flex:0 0 auto}.th2-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.th2-metric{min-height:112px;padding:16px;border:1px solid #e6dfdc;border-radius:17px;background:#fff;text-align:left;color:#27252a;cursor:pointer;box-shadow:0 4px 16px rgba(62,34,31,.035)}.th2-metric strong{display:block;font-size:30px;line-height:1;margin-bottom:9px}.th2-metric span{display:block;font-size:14px;line-height:1.3}.th2-metric[data-kind=waiting]{background:#f7f9fc}.th2-metric[data-kind=processing]{background:#fff8ec}.th2-metric[data-kind=validation]{background:#f0faf4}.th2-metric[data-kind=failed]{background:#fff3f2;color:#8b1c1c}.th2-metric:disabled{cursor:default;opacity:.58}.th2-metric:not(:disabled):hover{border-color:#b98c87}.th2-credit{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:18px 20px;border:1px solid #ebdedb;border-radius:17px;background:linear-gradient(135deg,#fff8f7,#fff)}.th2-credit-copy small{display:block;color:#756f73;margin-bottom:4px}.th2-credit-copy strong{font-size:28px;color:#8b1c1c}.th2-credit-copy span{color:#67636a;margin-left:5px}.th2-credit .btn{white-space:nowrap}.th2-section{display:grid;gap:12px}.th2-section-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.th2-section h2{font-size:20px;margin:0}.th2-list{background:#fff;border:1px solid #e7e2df;border-radius:17px;padding:0 18px}.th2-row{display:flex;width:100%;align-items:center;justify-content:space-between;gap:16px;padding:15px 0;border:0;border-bottom:1px solid #eee9e6;background:transparent;text-align:left;color:inherit;font:inherit;cursor:pointer}.th2-row:last-child{border-bottom:0}.th2-row-main{min-width:0}.th2-row-main strong{display:block;font-size:15px;line-height:1.35}.th2-row-main small{display:block;color:#6b6870;margin-top:5px;line-height:1.4}.th2-row-go{font-size:13px;font-weight:750;color:#8b1c1c;flex:0 0 auto}.th2-row:hover .th2-row-main strong{color:#8b1c1c}.th2-empty{padding:17px 0;margin:0;color:#496452}.th2-quick{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.th2-quick .btn{min-height:46px}.th2-notice{padding:16px 18px;border:1px solid #eadfda;border-radius:15px;background:#fff}.th2-notice h2{margin:0 0 8px}.th2-notice-list{display:grid}.th2-notice .th2-row{padding:12px 0}.th2-activity-time{font-size:12px;color:#7a757b;white-space:nowrap}.th2-error{padding:18px;border-radius:15px;background:#fff3f2;color:#7b2c27}
 @media(max-width:720px){.th2{gap:18px}.th2-head{align-items:center}.th2-head h1{font-size:27px}.th2-head p{font-size:14px}.th2-refresh{min-width:44px;padding:0 12px}.th2-metrics{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.th2-metric{min-height:100px;padding:14px}.th2-metric strong{font-size:28px}.th2-credit{padding:16px}.th2-credit-copy strong{font-size:26px}.th2-credit .btn{padding:0 12px}.th2-quick{grid-template-columns:repeat(2,minmax(0,1fr))}.th2-list{padding:0 15px}.th2-row{gap:10px}.th2-activity-time{display:none}}
 @media(max-width:420px){.th2-head h1{font-size:25px}.th2-credit{align-items:flex-start;flex-direction:column}.th2-credit .btn{width:100%}.th2-quick{grid-template-columns:1fr 1fr}.th2-quick .btn{padding:0 8px;font-size:13px}}
 `;document.head.appendChild(style);
}
async function renderTeacherHome(navigation){
 ensureTeacherHomeStyle();
 let d=null,credit=null;
 try{d=await catalogCall('home')}catch{}
 try{credit=await edge(API.credit,{action:'packages'})}catch{}
 if(!navigationCurrent(navigation))return;
 const first=(S.profile.full_name||'Professor').trim().replace(/^professor\s+/i,'').split(/\s+/)[0];
 const actions=[],register=(route,intent='',extra={})=>{const id=actions.length;actions.push({route,intent,...extra});return id};
 const metric=(value,label,kind,intent)=>{const n=Number(value||0),id=register('correction',intent);return `<button type="button" class="th2-metric" data-kind="${kind}" data-home-action="${id}" ${n===0?'disabled':''}><strong>${n}</strong><span>${esc(label)}</span></button>`};
 const balance=Number(credit?.balance),balanceText=Number.isFinite(balance)?String(balance):'—',creditAction=register('teacher-account','credits');
 const metrics=[metric(d?.pending,'A corrigir','waiting','uncorrected'),metric(d?.processing,'Em análise','processing','processing'),metric(d?.validation,'Prontas para validar','validation','validation'),metric(d?.failed,'Falhas','failed','failed')].join('');
 const quick=[['Nova proposta','proposals','create'],['Corrigir redações','correction',d?.pending?'uncorrected':d?.validation?'validation':d?.failed?'failed':''],['Importar alunos','teacher-organization','import'],['Nova turma','teacher-organization','class'],['Novo aluno','teacher-organization','student']].map(([label,route,intent])=>{const id=register(route,intent,{organization_id:d?.default_organization,class_id:intent==='class'?null:d?.default_class});return `<button type="button" class="btn soft-btn" data-home-action="${id}">${label}</button>`}).join('');
 const issues=[];
 for(const item of d?.issues||[]){const id=register('teacher-organization',item.kind,{organization_id:item.organization_id,class_id:item.class_id,student_name:item.student_name});issues.push(`<button type="button" class="th2-row" data-home-action="${id}"><span class="th2-row-main"><strong>${esc(item.label)}</strong></span><span class="th2-row-go">Abrir</span></button>`)}
 if(d&&!d.has_organizations){const id=register('teacher-organization','institution');issues.unshift(`<button type="button" class="th2-row" data-home-action="${id}"><span class="th2-row-main"><strong>Cadastre sua primeira instituição e turma</strong></span><span class="th2-row-go">Abrir</span></button>`)}
 const activities=(d?.activities||[]).slice(0,5).map(item=>{const id=register(item.route,'activity',{target:item.target}),date=new Date(item.at),formatted=Number.isNaN(date.getTime())?'':date.toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});return `<button type="button" class="th2-row" data-home-action="${id}"><span class="th2-row-main"><strong>${esc(item.label)}</strong><small>${esc(formatted)}</small></span><span class="th2-row-go">Abrir</span></button>`}).join('');
 $('view').innerHTML=`<section class="th2"><header class="th2-head"><div><h1>Painel inicial</h1><p>Olá, ${esc(first)}. Acompanhe correções, validações e pendências.</p></div><button type="button" class="btn ghost th2-refresh" id="homeRefresh" aria-label="Atualizar painel">Atualizar</button></header>${d?`<div class="th2-metrics">${metrics}</div>`:'<div class="th2-error">Não foi possível carregar as tarefas. Atualize para tentar novamente.</div>'}<section class="th2-credit"><div class="th2-credit-copy"><small>Seus créditos</small><strong>${balanceText}</strong><span>correções disponíveis</span></div><button type="button" class="btn soft-btn" data-home-action="${creditAction}">Ver créditos</button></section>${issues.length?`<section class="th2-notice"><h2>Organização necessária</h2><div class="th2-notice-list">${issues.join('')}</div></section>`:''}<section class="th2-section"><div class="th2-section-head"><h2>Ações rápidas</h2></div><div class="th2-quick">${quick}</div></section><section class="th2-section"><div class="th2-section-head"><h2>Atividades recentes</h2></div><div class="th2-list">${activities||'<p class="th2-empty">Nenhuma atividade recente.</p>'}</div></section></section>`;
 $('view').onclick=e=>{const button=e.target.closest('[data-home-action]');if(!button||button.disabled)return;const a=actions[Number(button.dataset.homeAction)];if(!a)return;
  if(a.route==='teacher-organization'){S.organizationIntent=a.intent;S.catalogSelection={organization_id:a.organization_id,class_id:a.class_id};S.homeStudentName=a.student_name||null;}
  if(a.route==='correction')S.homeCorrection={filter:a.intent==='activity'?'':a.intent,target:a.target};
  if(a.route==='proposals')S.homeProposal={intent:a.intent,ids:a.ids,target:a.target};
  navigate(a.route);
 };
 $('homeRefresh').onclick=()=>navigate('home');
}
