'use strict';
async function renderHome(){const [q,p]=await Promise.all([teacherQueue(),teacherProposals()]);const approved=q.filter(x=>x.score?.is_approved).length,pending=q.length-approved,visible=(p.recent||[]).filter(x=>x.is_visible_to_students).length;$('view').innerHTML=header('Início','Painel consolidado do professor.')+`<section class="grid cols4"><div class="card metric"><small>Na fila</small><b>${q.length}</b></div><div class="card metric"><small>Aguardando oficial</small><b>${pending}</b></div><div class="card metric"><small>Correções aprovadas</small><b>${approved}</b></div><div class="card metric"><small>Propostas publicadas</small><b>${visible}</b></div></section><section class="grid cols2" style="margin-top:12px"><article class="box"><div class="box-head"><h2>Fila recente</h2><p>Últimas redações disponíveis para correção.</p></div><div class="box-body list">${q.slice(0,5).map(x=>{const [s,c]=statusLabel(x);return `<div class="list-item"><div class="item-top"><div><div class="item-title">${esc(x.student_name)}</div><div class="item-meta">${esc(x.class_name)} · R${esc(x.round_number??'—')} · ${esc(x.theme||'Proposta')}</div></div><span class="pill ${c}">${s}</span></div></div>`}).join('')||'<div class="empty">Nenhuma redação na fila.</div>'}</div></article><article class="box"><div class="box-head"><h2>Propostas recentes</h2><p>Visão consolidada das propostas.</p></div><div class="box-body list">${(p.recent||[]).slice(0,5).map(r=>`<div class="list-item"><div class="item-top"><div><div class="item-title">R${esc(r.number??'—')} · ${esc(r.theme)}</div><div class="item-meta">${r.target_count||0} destinatário(s) · ${r.motivator_count||0} texto(s) motivador(es)</div></div><span class="pill ${r.is_visible_to_students?'ok':'warn'}">${r.is_visible_to_students?'Publicada':'Rascunho'}</span></div></div>`).join('')||'<div class="empty">Nenhuma proposta recente.</div>'}</div></article></section>`}

async function renderProposals(){
 const d=S.cache.proposalStage||(S.cache.proposalStage=structuredClone(await teacherProposals(true)));
 d.recent=d.recent||[];
 $('view').innerHTML=header('Propostas','Crie e organize suas propostas.',`<button class="btn primary" id="newProposal">Nova proposta</button>`)+`<div class="safe-note">Modo de teste: alterações locais, sem gravação no banco. Permanecem durante a navegação e são descartadas ao atualizar a página.</div><div id="proposalEditor"></div><div class="toolbar edit-filters"><label>Buscar proposta<input id="propSearch" type="search" placeholder="Tema ou número"></label><label>Exibir<select id="propFilter"><option value="all">Todas</option><option value="visible">Publicadas</option><option value="draft">Rascunhos</option><option value="hidden">Ocultas</option></select></label></div><div class="box"><div class="box-head"><h2>Propostas</h2><p id="propCount"></p></div><div class="box-body list" id="proposalList"></div></div>`;
 renderProposalList(d);
 $('newProposal').onclick=()=>proposalEditor(null,d);
 $('propSearch').oninput=()=>renderProposalList(d);$('propFilter').onchange=()=>renderProposalList(d);
 $('proposalList').onclick=e=>{const b=e.target.closest('[data-prop-action]');if(!b)return;const r=d.recent.find(x=>String(x.id)===b.dataset.id);if(!r)return;
 if(b.dataset.propAction==='edit')return proposalEditor(r,d);
 if(b.dataset.propAction==='toggle'){r._hidden=!r._hidden;renderProposalList(d);toast(r._hidden?'Proposta ocultada nesta simulação.':'Proposta restaurada nesta simulação.');}
 if(b.dataset.propAction==='delete'&&confirm('Excluir esta proposta apenas da simulação local?')){d.recent=d.recent.filter(x=>x!==r);if(d._editorId===r.id){d._editorToken=null;$('proposalEditor').innerHTML='';}renderProposalList(d);toast('Proposta excluída nesta simulação.');}
 };
}
function renderProposalList(d){
 const box=$('proposalList');if(!box)return;const search=($('propSearch')?.value||'').toLocaleLowerCase('pt-BR'),filter=$('propFilter')?.value||'all';
 const rows=d.recent.filter(r=>(!search||`${r.number||''} ${r.theme||''}`.toLocaleLowerCase('pt-BR').includes(search))&&(filter==='all'||filter==='hidden'&&r._hidden||filter==='visible'&&!r._hidden&&r.is_visible_to_students||filter==='draft'&&!r._hidden&&!r.is_visible_to_students));
 $('propCount').textContent=`${rows.length} de ${d.recent.length} proposta(s)`;
 box.innerHTML=rows.map(r=>`<div class="list-item"><div class="item-top"><div><div class="item-title">R${esc(r.number??'—')} · ${esc(r.theme)}</div><div class="item-meta">${fmtDate(r.due_date)} · ${r.target_count||0} turma(s) · ${r.motivator_count||0} motivador(es)</div></div><span class="pill ${r._hidden?'warn':r.is_visible_to_students?'ok':'warn'}">${r._hidden?'Oculta':r.is_visible_to_students?'Publicada':'Rascunho'}</span></div><div class="item-actions"><button class="btn soft-btn" data-prop-action="edit" data-id="${esc(r.id)}">Editar</button><button class="btn soft-btn" data-prop-action="toggle" data-id="${esc(r.id)}">${r._hidden?'Reexibir':'Ocultar'}</button><button class="btn ghost danger" data-prop-action="delete" data-id="${esc(r.id)}">Excluir</button></div></div>`).join('')||'<div class="empty">Nenhuma proposta para estes filtros.</div>';
}
async function proposalEditor(r,d){
 const ed=$('proposalEditor');if(!ed)return;const token={};d._editorToken=token;d._editorId=r?.id||null;
 ed.innerHTML='<div class="card">Abrindo editor…</div>';ed.scrollIntoView({behavior:'smooth',block:'start'});
 let detail=null;
 if(r&&!r._loaded&&!r._edited&&!String(r.id).startsWith('local-')){
  try{detail=await edge(API.proposal,{action:'get',round_id:r.id});}
  catch(e){if(d._editorToken!==token||!ed.isConnected)return;ed.innerHTML=`<div class="card"><p>${esc(e.message||'Não foi possível carregar os detalhes da proposta.')}</p><button class="btn soft-btn" id="retryProp">Tentar novamente</button><button class="btn ghost" id="closeProp">Fechar</button></div>`;$('retryProp').onclick=()=>proposalEditor(r,d);$('closeProp').onclick=()=>{d._editorToken=null;ed.innerHTML=''};return;}
 }
 if(d._editorToken!==token||!ed.isConnected)return;
 const p={...(r||{}),...(detail?.proposal||{})},mot=detail?.motivators||p._motivators||[],targets=detail?.targets||p._targets||[],orgs=d.organizations||[],project=one(p.project)||one(p.projects),initialOrg=project?.organization_id||p.organization_id||orgs[0]?.id||'';
 if(r&&detail)Object.assign(r,p,{_motivators:structuredClone(mot),_targets:structuredClone(targets),_loaded:true});
 const selected=new Set(targets.map(t=>t.class_id).filter(Boolean));
 const classChecks=orgId=>{const a=d.classes_by_org?.[orgId]||[];return a.map(c=>`<label class="check-row"><input type="checkbox" value="${esc(c.id)}" ${selected.has(c.id)?'checked':''}><span>${esc(c.name)}</span></label>`).join('')||'<p>Nenhuma turma disponível nesta instituição.</p>'};
 ed.innerHTML=`<div class="box local-editor"><div class="box-head editor-head"><h2>${r?'Editar proposta':'Nova proposta'}</h2><button id="closeProp" class="btn ghost">Fechar</button></div><div class="box-body"><div class="grid cols2"><label class="field"><small>Instituição</small><select id="peOrg">${orgs.map(o=>`<option value="${esc(o.id)}" ${o.id===initialOrg?'selected':''}>${esc(o.name)}</option>`).join('')}</select></label><label class="field"><small>Prazo (opcional)</small><input id="peDue" type="date" value="${esc(String(p.due_date||'').slice(0,10))}"></label></div><label class="field"><small>Tema</small><input id="peTheme" value="${esc(p.theme||'')}"></label><label class="field"><small>Comando</small><textarea id="peCommand">${esc(p.proposal_command||'')}</textarea></label><label class="field"><small>Entenda o que o tema está pedindo</small><textarea id="peUnderstand">${esc(p.understand_prompt||'')}</textarea></label><div class="field"><small>Textos motivadores</small><div id="peMotList">${(mot.length?mot:[{body:''}]).map((m,i)=>`<label class="field"><small>Texto ${i+1}</small><textarea data-motivator>${esc(m.body||'')}</textarea></label>`).join('')}</div><button class="btn soft-btn" id="addMot">Adicionar texto</button></div><div class="field"><small>Turmas destinatárias</small><div class="item-actions"><button class="btn ghost" id="selectPropClasses">Selecionar todas</button><button class="btn ghost" id="clearPropClasses">Limpar seleção</button></div><div id="peClasses" class="check-grid">${classChecks(initialOrg)}</div></div><div id="propStatus" class="form-status" role="status" aria-live="polite"></div><div class="item-actions editor-footer"><button id="saveProp" class="btn primary">Salvar alterações</button><button id="draftProp" class="btn soft-btn">Salvar como rascunho</button><button id="publishProp" class="btn soft-btn">Publicar no teste</button></div></div></div>`;
 $('closeProp').onclick=()=>{d._editorToken=null;ed.innerHTML=''};
 $('peOrg').onchange=()=>{selected.clear();$('peClasses').innerHTML=classChecks($('peOrg').value)};
 $('selectPropClasses').onclick=()=>ed.querySelectorAll('#peClasses input').forEach(x=>x.checked=true);
 $('clearPropClasses').onclick=()=>ed.querySelectorAll('#peClasses input').forEach(x=>x.checked=false);
 $('addMot').onclick=()=>{const label=document.createElement('label');label.className='field';label.innerHTML=`<small>Texto ${ed.querySelectorAll('[data-motivator]').length+1}</small><textarea data-motivator></textarea>`;$('peMotList').append(label);label.querySelector('textarea').focus()};
 const apply=publish=>{
  const status=$('propStatus'),theme=$('peTheme').value.trim(),command=$('peCommand').value.trim(),orgId=$('peOrg').value,values=[...ed.querySelectorAll('[data-motivator]')].map(x=>x.value.trim()),classIds=[...ed.querySelectorAll('#peClasses input:checked')].map(x=>x.value);
  const fail=text=>{status.textContent=text;status.scrollIntoView({block:'nearest'})};
  if(!orgId||!theme||!command)return fail('Preencha instituição, tema e comando.');
  if(!values.some(Boolean))return fail('Inclua ao menos um texto motivador.');
  if(publish&&!classIds.length)return fail('Selecione pelo menos uma turma para publicar.');
  if(!r){r={id:'local-'+crypto.randomUUID(),number:Math.max(0,...d.recent.map(x=>Number(x.number)||0))+1};d.recent.unshift(r);d._editorId=r.id;}
  Object.assign(r,{theme,proposal_command:command,understand_prompt:$('peUnderstand').value.trim(),due_date:$('peDue').value||null,is_visible_to_students:publish,status:publish?'sent':'planned',organization_id:orgId,project:{organization_id:orgId},target_count:classIds.length,motivator_count:values.filter(Boolean).length,_targets:classIds.map(class_id=>({class_id})),_motivators:values.map((body,i)=>({...mot[i],body})).filter(x=>x.body),_edited:true,_loaded:true});
  renderProposalList(d);status.textContent='Alterações salvas nesta simulação. Nenhum dado foi gravado no banco.';toast('Proposta atualizada no teste.');
 };
 $('saveProp').onclick=()=>apply(!!r?.is_visible_to_students);$('draftProp').onclick=()=>apply(false);$('publishProp').onclick=()=>apply(true);$('peTheme').focus({preventScroll:true});
}

async function loadDirectory(){if(S.cache.directory)return S.cache.directory;const [students,enr,classes,orgs,rounds]=await Promise.all([rest('students?is_active=eq.true&select=id,full_name,organization_id&order=full_name'),rest('enrollments?is_active=eq.true&select=student_id,class_id'),rest('classes?is_active=eq.true&select=id,name'),rest('organizations?select=id,name&order=name'),rest('rounds?is_visible_to_students=eq.true&status=neq.planned&select=id,number,theme,project_id,projects(organization_id)&order=number')]);S.cache.directory={students,enr,classes,orgs,rounds};return S.cache.directory}
async function renderLive(){const d=await loadDirectory();$('view').innerHTML=header('Ao vivo','Captura consolidada com regra definitiva de uma página.')+`<section class="capture"><div class="box"><div class="box-head"><h2>Identificação da redação</h2><p>Instituição → turma → aluno → proposta.</p></div><div class="box-body upload-box"><label class="field"><small>Instituição</small><select id="lvOrg"></select></label><label class="field"><small>Turma</small><select id="lvClass"></select></label><label class="field"><small>Aluno</small><select id="lvStudent"></select></label><label class="field"><small>Proposta</small><select id="lvRound"></select></label><div class="drop"><b>Uma página por redação</b><p class="muted">Use câmera ou escolha uma imagem JPG, PNG ou WEBP.</p><input id="lvFile" type="file" accept="image/jpeg,image/png,image/webp" capture="environment"></div><button id="lvSend" class="btn primary" disabled>Enviar para a fila</button><div class="safe-note">Envio real permanece desativado. A seleção e a prévia são validadas localmente.</div></div></div><div class="box"><div class="box-head"><h2>Prévia</h2><p>A redação deve ocupar exatamente uma página.</p></div><div class="box-body"><div class="preview" id="lvPreview"><div class="preview-placeholder">Selecione uma imagem para visualizar.</div></div></div></div></section>`;liveFill(d);$('lvOrg').onchange=()=>liveFill(d,'org');$('lvClass').onchange=()=>liveFill(d,'class');$('lvFile').onchange=e=>{const f=e.target.files?.[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>15*1024*1024){e.target.value='';toast('Use apenas uma imagem JPG, PNG ou WEBP de até 15 MB.');return}const u=URL.createObjectURL(f);$('lvPreview').innerHTML=`<img src="${u}" alt="Prévia da redação">`;$('lvSend').disabled=false};$('lvSend').onclick=()=>safeMessage('Envio da redação para a fila')}
function liveFill(d,change){const classBy=new Map(d.classes.map(x=>[x.id,x])),orgSel=$('lvOrg'),clsSel=$('lvClass'),stSel=$('lvStudent'),rdSel=$('lvRound');if(!orgSel.options.length)orgSel.innerHTML='<option value="">Selecione</option>'+d.orgs.map(o=>`<option value="${o.id}">${esc(o.name)}</option>`).join('');const oid=orgSel.value,studentIds=new Set(d.students.filter(s=>s.organization_id===oid).map(s=>s.id)),classIds=new Set(d.enr.filter(e=>studentIds.has(e.student_id)).map(e=>e.class_id));const keepC=change==='org'?'':clsSel.value;clsSel.innerHTML='<option value="">Selecione</option>'+d.classes.filter(c=>classIds.has(c.id)).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');if([...clsSel.options].some(o=>o.value===keepC))clsSel.value=keepC;const cid=clsSel.value,ids=cid?new Set(d.enr.filter(e=>e.class_id===cid).map(e=>e.student_id)):studentIds;stSel.innerHTML='<option value="">Selecione</option>'+d.students.filter(s=>ids.has(s.id)).map(s=>`<option value="${s.id}">${esc(s.full_name)}</option>`).join('');rdSel.innerHTML='<option value="">Selecione</option>'+d.rounds.filter(r=>one(r.projects)?.organization_id===oid).map(r=>`<option value="${r.id}">R${esc(r.number??'—')} · ${esc(r.theme)}</option>`).join('')}
