'use strict';
window.WritingSupport=Object.freeze({
 stages:{
  introduction:{fields:[['pergunta','Pergunta do tema'],['recorte','Recorte'],['posicao','Posição'],['ideias','Ideias']],objective:'Antes de formular a tese, descubra o que o tema pede: desafios, fatores, relação, perspectivas ou consequências. Apresente o tema, delimite o problema e deixe clara a posição que você defenderá.',structure:'Contextualização → recorte do problema → tese. Essa sequência é um apoio, não uma fórmula obrigatória.',mistake:'Apresentar um assunto amplo sem explicar qual problema será discutido.',questions:['O tema pede explicar um obstáculo, causa, relação, perspectiva ou efeito?','Qual pergunta central o tema exige responder?','Qual aspecto do tema você vai discutir?','Que posição pretende defender?'],review:['Seu texto delimita um problema?','A posição que você defenderá está clara?']},
  development1:{fields:[['argumento','1. Ideia'],['explicacao','2. Explicação'],['referencia','3. Repertório'],['consequencia','4. Consequência'],['fechamento','5. Fechamento']],prompts:{argumento:'O que quero provar?',explicacao:'Por que ou como isso acontece?',referencia:'Qual referência e qual ideia dela ajudam a provar meu argumento?',consequencia:'O que isso provoca?',fechamento:'O que ficou demonstrado?'},objective:'Construa o argumento em cinco movimentos. Cada parte precisa fazer o raciocínio avançar.',structure:'Ideia → Explicação → Repertório → Consequência → Fechamento. São funções do parágrafo, não cinco frases obrigatórias.',mistake:'Citar uma referência sem interpretar sua ideia e explicar o que ela prova.',questions:['Minha ideia responde à pergunta do tema?','Como ou por que o problema acontece?','Que ideia extraio da referência e o que ela ajuda a provar?','Que consequência esse mecanismo produz?','O que ficou demonstrado em relação à tese?'],review:['Você explicou o caminho entre a ideia e a consequência?','Se retirar o repertório, qual explicação se perde?','A referência foi interpretada e relacionada ao argumento?','O fechamento mostra o que ficou demonstrado?']},
  development2:{fields:[['argumento','1. Ideia'],['explicacao','2. Explicação'],['referencia','3. Repertório'],['consequencia','4. Consequência'],['fechamento','5. Fechamento']],prompts:{argumento:'O que quero provar?',explicacao:'Por que ou como isso acontece?',referencia:'Qual referência e qual ideia dela ajudam a provar meu argumento?',consequencia:'O que isso provoca?',fechamento:'O que ficou demonstrado?'},objective:'Desenvolva uma segunda ideia que avance a tese sem repetir o primeiro argumento. Organize-a nos cinco movimentos.',structure:'Ideia → Explicação → Repertório → Consequência → Fechamento. São funções do parágrafo, não cinco frases obrigatórias.',mistake:'Citar uma referência sem interpretar sua ideia e explicar o que ela prova.',questions:['Como esta ideia avança a tese sem repetir o primeiro desenvolvimento?','Como ou por que o problema acontece?','Que ideia extraio da referência e o que ela ajuda a provar?','Que consequência esse mecanismo produz?','O que ficou demonstrado em relação à tese?'],review:['Você explicou o caminho entre a ideia e a consequência?','Se retirar o repertório, qual explicação se perde?','A referência foi interpretada e relacionada ao argumento?','O fechamento mostra o que ficou demonstrado?']},
  conclusion:{fields:[['agente','Agente'],['acao','Ação'],['meio','Meio'],['finalidade','Finalidade'],['detalhamento','Detalhamento']],objective:'Retome o problema e proponha uma intervenção coerente com a discussão.',structure:'Quem age? O que faz? Como? Para quê? Que detalhe torna a proposta compreensível? Uma segunda intervenção é opcional.',mistake:'Propor uma medida genérica que não enfrenta o problema discutido.',questions:['Quem pode enfrentar o problema que você explicou?','Como essa ação seria realizada e com qual finalidade?'],review:['A proposta responde ao problema discutido?','Agente, ação, meio, finalidade e detalhamento estão compreensíveis?']}
 },
 decode(plan){try{const v=JSON.parse(plan);if(v?.format==='writing-plan-v1'&&v.fields&&typeof v.fields==='object'&&!Array.isArray(v.fields)&&typeof v.notes==='string')return v;}catch{}return{format:'writing-plan-v1',fields:{},notes:String(plan||'')};},
 encode(fields,notes){return Object.values(fields).some(v=>v.trim())?JSON.stringify({format:'writing-plan-v1',fields,notes}):notes;},
 question(action,stage){const method=['development1','development2'].includes(stage)?' Use os cinco movimentos: Ideia (o que provar), Explicação (como/por quê), Repertório (referência, ideia extraída, relação e função), Consequência (efeito) e Fechamento (o que demonstrou). Identifique um movimento a melhorar. Pergunte o que a referência prova e qual explicação se perderia sem ela. Não exija cinco frases nem preencha pelo aluno.':stage==='introduction'?' Primeiro ajude a interpretar a pergunta e a relação exigidas pelo tema; depois a tese.':' Ajude a construir uma intervenção executável ligada aos problemas discutidos: agente, ação, meio, finalidade e detalhamento.';const label=window.WritingStages.stages[stage].label;return (({ideas:`Estou sem ideias para ${label}. Faça perguntas para me ajudar a decidir um caminho, sem escrever por mim.`,analyse:`Analise meu trecho de ${label}. Priorize uma dificuldade e proponha uma tarefa de revisão, sem reescrever.`,plan:`Reveja meu planejamento de ${label} e sua relação com o texto, sem fornecer uma resposta pronta.`,theme:'Ajude-me a entender o tema e o comando: explique o recorte e faça perguntas, sem fornecer tese ou argumentos prontos.',repertoire:'Busque até três fontes confiáveis pertinentes ao tema e ao meu planejamento. Mostre as referências para eu ler, sem aplicar o repertório ao meu argumento.'})[action]||'Preciso de uma orientação.')+method;}
});
