'use strict';
window.WritingSupport=Object.freeze({
 stages:{
  introduction:{fields:[['recorte','Recorte'],['posicao','Posição'],['ideias','Ideias']],objective:'Apresente o tema, delimite o problema e deixe clara a posição que você defenderá.',structure:'Contextualização → recorte do problema → tese. Essa sequência é um apoio, não uma fórmula obrigatória.',mistake:'Apresentar um assunto amplo sem explicar qual problema será discutido.',questions:['Qual aspecto do tema você vai discutir?','Que posição pretende defender?'],review:['Seu texto delimita um problema?','A posição que você defenderá está clara?']},
  development1:{fields:[['argumento','Argumento'],['explicacao','Explicação'],['referencia','Referência'],['relacao','Relação com o tema']],objective:'Desenvolva o primeiro argumento com explicação, evidência e análise.',structure:'Argumento → explicação → repertório pertinente → análise. Mostre como isso sustenta sua tese.',mistake:'Citar uma referência sem explicar sua relação com o argumento.',questions:['Por que esse argumento sustenta sua posição?','O que a referência ajuda a compreender?'],review:['Você explicou como o problema acontece?','O repertório contribui para o raciocínio?']},
  development2:{fields:[['argumento','Segundo argumento'],['explicacao','Explicação'],['referencia','Referência'],['progressao','O que acrescenta']],objective:'Acrescente um argumento que faça a discussão avançar.',structure:'Novo argumento → explicação → repertório → análise. Causa e consequência são uma possibilidade, não uma exigência.',mistake:'Repetir o primeiro desenvolvimento com outras palavras.',questions:['O que este argumento acrescenta ao anterior?','Como ele se relaciona com sua tese?'],review:['Existe uma ideia nova neste parágrafo?','A relação com o argumento anterior é coerente?']},
  conclusion:{fields:[['agente','Agente'],['acao','Ação'],['meio','Meio'],['finalidade','Finalidade'],['detalhamento','Detalhamento']],objective:'Retome o problema e proponha uma intervenção coerente com a discussão.',structure:'Quem age? O que faz? Como? Para quê? Que detalhe torna a proposta compreensível? Uma segunda intervenção é opcional.',mistake:'Propor uma medida genérica que não enfrenta o problema discutido.',questions:['Quem pode enfrentar o problema que você explicou?','Como essa ação seria realizada e com qual finalidade?'],review:['A proposta responde ao problema discutido?','Agente, ação, meio, finalidade e detalhamento estão compreensíveis?']}
 },
 decode(plan){try{const v=JSON.parse(plan);if(v?.format==='writing-plan-v1'&&v.fields&&typeof v.fields==='object'&&!Array.isArray(v.fields)&&typeof v.notes==='string')return v;}catch{}return{format:'writing-plan-v1',fields:{},notes:String(plan||'')};},
 encode(fields,notes){return Object.values(fields).some(v=>v.trim())?JSON.stringify({format:'writing-plan-v1',fields,notes}):notes;},
 question(action,stage){const label=window.WritingStages.stages[stage].label;return ({ideas:`Estou sem ideias para ${label}. Faça perguntas para me ajudar a decidir um caminho, sem escrever por mim.`,analyse:`Analise meu trecho de ${label}. Priorize uma dificuldade e proponha uma tarefa de revisão, sem reescrever.`,plan:`Reveja meu planejamento de ${label} e sua relação com o texto, sem fornecer uma resposta pronta.`,theme:'Ajude-me a entender o tema e o comando: explique o recorte e faça perguntas, sem fornecer tese ou argumentos prontos.',repertoire:'Busque até três fontes confiáveis pertinentes ao tema e ao meu planejamento. Mostre as referências para eu ler, sem aplicar o repertório ao meu argumento.'})[action]||'Preciso de uma orientação.';}
});
