const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict');
const d=new JSDOM('',{runScripts:'outside-only'}),w=d.window;
w.esc=x=>String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');w.fmtDate=x=>x;
w.eval(fs.readFileSync('ranking-management.e12.js','utf8')+';window.platformCostTable=platformCostTable;window.platformAccessPanel=platformAccessPanel;window.bindPlatformAccess=bindPlatformAccess;window.platformDashboardHtml=platformDashboardHtml;window.platformPersonName=platformPersonName;window.platformAccessDate=platformAccessDate;window.platformReportHTML=platformReportHTML;');
assert.equal(w.platformPersonName('IRANI RIBEIRO SOUSA DE MENEZES &#x20;'),'Irani Ribeiro Sousa de Menezes');assert.equal(w.platformPersonName('João McDonald'),'João McDonald');assert.match(w.platformAccessDate('2026-10-02T15:00:00Z'),/12:00/);assert.match(w.platformAccessDate(null),/Nenhum login/);
const report={since:'a',until:'b',services:[{name:'Ao Vivo <script>',requests:3,completed:1,failed:2,cost_usd:1,known_cost_count:2,missing_cost_count:1,average_attempt_usd:null,average_completed_usd:null}],fx:{rate:5,available:true,date:'02/10/2026',source:'BCB'}};
w.document.body.innerHTML=w.platformReportHTML(report,'costs');assert.match(w.document.body.textContent,/R\$\s*5,0000/);assert.match(w.document.body.textContent,/Indisponível/);assert.equal(w.document.querySelector('script'),null);
report.fx.available=false;assert.match(w.platformReportHTML(report,'costs'),/Cotação indisponível/);
report.failure_summary=[{service:'Ao Vivo',stage:'Verificação de conteúdo',type:'Conteúdo inválido',requests:3,known_cost_count:0}];assert.match(w.platformReportHTML(report,'failures'),/Conteúdo inválido/);assert.match(w.platformReportHTML(report,'failures'),/Verificação de conteúdo/);const accessData={last_logins:[{name:'Aluno exemplo',role:'student',access_count:3},{name:'Professor exemplo',role:'teacher',access_count:2}]};w.document.body.innerHTML=w.platformAccessPanel(accessData);w.bindPlatformAccess(w.document.body,accessData);w.document.querySelector('[data-access-role="student"]').click();assert.match(w.document.body.textContent,/3 acesso/);assert.doesNotMatch(w.document.querySelector('[data-access-list]').textContent,/Professor exemplo/);w.document.querySelector('[data-access-role="teacher"]').click();assert.match(w.document.body.textContent,/2 acesso/);assert.doesNotMatch(w.document.querySelector('[data-access-list]').textContent,/Aluno exemplo/);w.document.querySelector('[data-access-role="all"]').click();assert.match(w.document.body.textContent,/5 acesso/);assert.match(w.platformDashboardHtml({accounts:{active:4}}),/Receita total acumulada/);const html=w.platformDashboardHtml({accounts:{active:4},fx:{available:true,rate:5},services:[{name:'Correções',requests:3,deliveries:1,cost_usd:2,known_cost_count:2,missing_cost_count:1,known_average_completed_usd:2}]});assert.doesNotMatch(html,/Receita nos últimos 30 dias|<h2>Falhas por tipo e local/);assert.match(html,/Custos de IA por tipo/);assert.match(html,/10,0000/);assert.match(html,/Parcial/);d.window.close();console.log('PASS admin costs: BRL, missing costs, escaping, name case and Brasilia login time');
