'use strict';
const fs=require('fs'),assert=require('assert/strict'),{JSDOM}=require('jsdom');
const html=fs.readFileSync('index.html','utf8'),boot=fs.readFileSync('boot.e12.js','utf8');
const tick=()=>new Promise(r=>setImmediate(r));
async function fixture({callback=false,pending=false,session=false,url='https://app.versaoprofessor.com/',edgeFail=false}={}){
 const dom=new JSDOM(html,{url,runScripts:'outside-only'}),w=dom.window;await new Promise(r=>w.document.addEventListener('DOMContentLoaded',r,{once:true}));
 const s={access_token:'a',refresh_token:'b',expires_at:Math.floor(Date.now()/1000)+3600,user:{id:'teacher',user_metadata:{full_name:'Nome Google'}}};
 let stored=session?s:null,calls=[],routes=[],clears=0,saves=0;
 w.S={session:null,profile:null,cache:{}};w.readSession=()=>stored;w.saveSession=x=>{stored=x;saves++};w.clearSession=()=>{stored=null;clears++};w.signIn=async(...args)=>{calls.push({password:args});return s};w.signInPin=async(...args)=>{calls.push({pin:args});return s};w.refreshSession=async()=>s;w.profile=async()=>{if(pending)throw Object.assign(Error('Incomplete'),{code:'GOOGLE_SIGNUP_REQUIRED'});w.S.profile={role:'teacher'};};w.buildNav=()=>{};w.navigate=x=>routes.push(x);w.invalidateNavigation=()=>{};
 w.VersaoCaptcha={mount(){},reset(){},token(){return 'captcha-ok'}};w.VersaoGoogle={mount(){},isCallback:()=>callback,receive:async()=>s};
 w.edge=async(slug,body)=>{calls.push({slug,body});if(edgeFail)throw Error('Falha de teste');pending=false;return{ok:true,created:true}};
 w.eval(boot);await tick();return{w,dom,calls,routes,get clears(){return clears},get saves(){return saves}};
}
(async()=>{
 let f=await fixture();const q=id=>f.w.document.getElementById(id),select=q('loginAccessType');assert.equal(select.querySelector('[value=student]').textContent,'Estudante · PIN');assert.equal(select.querySelector('[value=independent]').textContent,'Estudante · E-mail');select.value='student';select.onchange();assert(q('emailField').classList.contains('hidden'));assert(q('authLinks').classList.contains('hidden'));select.value='independent';select.onchange();assert(!q('emailField').classList.contains('hidden'));assert(q('classCodeField').classList.contains('hidden'));assert.equal(q('registerLink').textContent,'Quero criar minha conta');select.value='teacher';select.onchange();assert.equal(q('registerLink').textContent,'Criar conta de professor');f.dom.window.close();
 f=await fixture({callback:true});assert.deepEqual(f.routes,['home']);assert.equal(f.saves,1);f.dom.window.close();
 f=await fixture({callback:true,pending:true});assert.equal(f.routes.length,0);assert(!f.w.document.getElementById('googleSignupForm').classList.contains('hidden'));assert(f.w.document.getElementById('loginForm').classList.contains('hidden'));assert.equal(f.w.document.getElementById('googleName').value,'Nome Google');const form=f.w.document.getElementById('googleSignupForm');await form.onsubmit({preventDefault(){}});assert.equal(f.calls.length,0);f.w.document.getElementById('googleTerms').checked=true;await form.onsubmit({preventDefault(){}});assert.deepEqual(f.routes,['home']);assert.equal(f.calls[0].body.action,'google_complete');assert(!('actor' in f.calls[0].body));f.dom.window.close();
 f=await fixture({session:true,pending:true,edgeFail:true});f.w.document.getElementById('googleTerms').checked=true;await f.w.document.getElementById('googleSignupForm').onsubmit({preventDefault(){}});assert.match(f.w.document.getElementById('googleStatus').textContent,/Falha/);assert.equal(f.routes.length,0);f.w.document.getElementById('googleCancel').click();assert(f.w.document.getElementById('googleSignupForm').classList.contains('hidden'));assert(!f.w.document.getElementById('loginForm').classList.contains('hidden'));assert.equal(f.clears,1);f.dom.window.close();
 f=await fixture();f.w.document.getElementById('email').value='teacher@example.com';f.w.document.getElementById('password').value='untouched';await f.w.document.getElementById('loginForm').onsubmit({preventDefault(){}});assert.equal(f.calls[0].password[3],'captcha-ok');assert.deepEqual(f.routes,['home']);f.dom.window.close();
 f=await fixture({url:'https://app.versaoprofessor.com/?acesso=aluno'});assert(f.w.document.getElementById('googleAccess').classList.contains('hidden'));f.w.document.getElementById('classCode').value='abcdefabcdef';f.w.document.getElementById('studentPin').value='12345678';await f.w.document.getElementById('loginForm').onsubmit({preventDefault(){}});assert.equal(f.calls[0].pin[1],'12345678');f.dom.window.close();
 f=await fixture({url:'https://app.versaoprofessor.com/#type=recovery&access_token=secret'});assert.equal(f.w.document.getElementById('authTitle').textContent,'Definir nova senha');assert.equal(f.routes.length,0);assert.equal(f.w.location.hash,'');f.dom.window.close();
 console.log('PASS boot: Google existing/new/reloaded accounts, consent, backend failure/cancel, password CAPTCHA, student PIN and password recovery.');
})().catch(e=>{console.error(e);process.exitCode=1});
