'use strict';
const {PGlite}=require('@electric-sql/pglite'),fs=require('fs'),assert=require('node:assert/strict');
(async()=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema private;
 create table profiles(id uuid primary key,role text,approval_status text);
 create table live_essays(id uuid primary key,owner_id uuid,input_text text,theme text,theme_origin text,theme_confirmed_at timestamptz,deleted_at timestamptz);
 create table live_jobs(id uuid primary key,essay_id uuid,owner_id uuid,purpose text,status text default 'processing',theme_snapshot text,theme_origin text,model text,credit_status text,result jsonb,usage jsonb,error_message text,completed_at timestamptz);
 create table live_files(essay_id uuid);create table live_input_checks(owner_id uuid,essay_id uuid,status text);
 create table correction_credit_wallets(profile_id uuid primary key,balance integer);
 create table ledger(key text primary key,amount integer);
 create function private.ensure_student_trial(uuid) returns void language sql as 'select';
 create function private.ensure_teacher_freemium(uuid) returns void language sql as 'select';
 create function private.credit_wallet_add(actor uuid,amount integer,kind text,k text,meta jsonb) returns integer language plpgsql as $$declare b integer;begin
 insert into public.ledger values(k,amount) on conflict do nothing;if not found then select balance into b from public.correction_credit_wallets where profile_id=actor;return b;end if;
 update public.correction_credit_wallets set balance=balance+amount where profile_id=actor and balance+amount>=0 returning balance into b;
 if not found then raise exception 'Saldo insuficiente.';end if;return b;end $$;`);
 await db.exec(fs.readFileSync('tests/fixtures/live-credit-rpcs.sql','utf8'));
 await db.exec(fs.readFileSync('backend/writing/supabase/migrations/20261007195224_live_partial_scope.sql','utf8'));
 await db.exec(fs.readFileSync('backend/writing/supabase/migrations/20261007210939_partial_theme_inference.sql','utf8'));
 const actor='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002',essay='00000000-0000-4000-8000-000000000003',job='00000000-0000-4000-8000-000000000004',job2='00000000-0000-4000-8000-000000000005';
 const text='Trecho sintético para análise parcial. '.repeat(5);
 await db.query("insert into profiles values($1,'teacher','approved'),($2,'teacher','approved')",[actor,other]);
 await db.query('insert into correction_credit_wallets values($1,2)',[actor]);
 await db.query("insert into live_essays(id,owner_id,input_text,theme,theme_origin,theme_confirmed_at,correction_scope) values($1,$2,$3,'Tema sintético de teste','provided',now(),'introduction')",[essay,actor,text]);
 await db.query("insert into live_input_checks values($1,$2,'valid')",[actor,essay]);
 const start=async(id=job,owner=actor,purpose='correction')=>(await db.query('select start_live_job($1,$2,$3,$4,$5) as value',[owner,essay,id,purpose,'synthetic'])).rows[0].value;
 const balance=async()=>(await db.query('select balance from correction_credit_wallets')).rows[0].balance;
 let claim=await start();assert.equal(claim.claimed,true);assert.equal(claim.job.correction_scope,'introduction');assert.equal(claim.job.input_snapshot,text);assert.equal(await balance(),1);
 assert.equal((await start()).claimed,false);assert.equal((await start(job2)).claimed,false);assert.equal(await balance(),1);
 await assert.rejects(start(job2,other));
 await assert.rejects(db.query("update live_essays set correction_scope='conclusion' where id=$1",[essay]));
 await assert.rejects(db.query("update live_essays set input_text='Texto alterado' where id=$1",[essay]));
 await assert.rejects(db.query("update live_jobs set input_snapshot='Outro texto' where id=$1",[job]));
 const finish=async(error,result=null)=>(await db.query('select finish_live_job($1,$2,$3,null,$4) as value',[actor,job,result,error])).rows[0].value;
 assert.equal((await finish('Falha sintética')).credit_status,'refunded');assert.equal(await balance(),2);
 await finish('Falha repetida');assert.equal(await balance(),2);assert.equal((await start()).claimed,false);
 claim=await start(job2);assert.equal(claim.claimed,true);assert.equal(await balance(),1);
 await db.query('select finish_live_job($1,$2,$3,null,null)',[actor,job2,{mode:'partial'}]);assert.equal(await balance(),1);
 await db.query('select finish_live_job($1,$2,null,null,$3)',[actor,job2,'Falha tardia']);assert.equal(await balance(),1);
 const beforeTheme=await balance();const theme=await start('00000000-0000-4000-8000-000000000006',actor,'theme');assert.equal(theme.claimed,true);assert.equal(theme.job.credit_status,'none');assert.equal(theme.job.input_snapshot,text);assert.equal(await balance(),beforeTheme);assert.equal((await start('00000000-0000-4000-8000-000000000006',actor,'theme')).claimed,false);assert.equal(await balance(),beforeTheme);
 const acl=await db.query("select has_function_privilege('anon','private.live_partial_snapshot()','execute') a,has_function_privilege('authenticated','private.live_partial_snapshot()','execute') u");assert.equal(acl.rows[0].a,false);assert.equal(acl.rows[0].u,false);
 await db.close();console.log('PASS SQL local: snapshot imutável, isolamento, reserva1, repetição sem débito, estorno único e resultado terminal preservado. Ledger local simulado; sem banco remoto.');
})().catch(e=>{console.error(e);process.exitCode=1;});
