import {validateEvidence,QUALITY_VERSION} from './correction-quality.ts';
const VALID_SCORES=new Set([0,40,80,120,160,200]);
const SCORING_CALIBRATION='c2-c3-2026-09-22';
export function schema(){
      const competence=()=>({type:'object',additionalProperties:false,properties:{score:{type:'integer',enum:[0,40,80,120,160,200]},diagnostic:{type:'string',maxLength:220}},required:['score','diagnostic']})
      return {type:'object',additionalProperties:false,properties:{transcription:{type:'string'},syntax_assessment:{type:'string'},reading_notes:{type:'string'},proposal_complete:{type:'boolean'},essay_status:{type:'string',enum:['regular','zero_candidate','uncertain']},zero_reason:{type:'string'},c1_deviations:{type:'array',items:{type:'object',additionalProperties:false,properties:{original:{type:'string'},correction:{type:'string'},rule:{type:'string'},category:{type:'string'},location:{type:'string'},evidence:{type:'string'}},required:['original','correction','rule','category','location','evidence']}},repertoire_checks:{type:'array',items:{type:'object',additionalProperties:false,properties:{reference:{type:'string'},classification:{type:'string',enum:['confirmada','contradita','não confirmada']},analysis:{type:'string'},source_url:{type:'string'}},required:['reference','classification','analysis','source_url']}},c5_check:{type:'object',additionalProperties:false,properties:{agent:{type:'string'},action:{type:'string'},means:{type:'string'},purpose:{type:'string'},detail:{type:'string'},human_rights:{type:'string'},argument_alignment:{type:'string'}},required:['agent','action','means','purpose','detail','human_rights','argument_alignment']},main_strength:{type:'string',maxLength:280},next_step:{type:'string',maxLength:280},improvement_priority:{type:'string'},reading_quality:{type:'string',enum:['good','partial','poor']},needs_manual_review:{type:'boolean'},manual_review_reason:{type:'string'},theme_adherence:{type:'string',enum:['adequate','partial','off_topic']},motivating_text_copy:{type:'string',enum:['none','possible','relevant']},competencies:{type:'object',additionalProperties:false,properties:{C1:competence(),C2:competence(),C3:competence(),C4:competence(),C5:competence()},required:['C1','C2','C3','C4','C5']},alerts:{type:'array',items:{type:'string'},maxItems:6}},required:['main_strength','next_step','syntax_assessment','reading_notes','proposal_complete','essay_status','zero_reason','transcription','c1_deviations','repertoire_checks','c5_check','improvement_priority','reading_quality','needs_manual_review','manual_review_reason','theme_adherence','motivating_text_copy','competencies','alerts']}
    }

export function normalizeResult(raw,sources=[]){
      if(raw?.reading_quality==='poor')throw new Error('A imagem não permite uma correção segura. Refaça a foto com boa iluminação e foco, sem cortar linhas. Use flash se necessário, evitando reflexos.')
      if(!String(raw?.transcription||'').trim())throw new Error('Não foi possível confirmar a transcrição da redação. Refaça a foto.')
      const evidence=validateEvidence(raw,sources),comps={}
      for(const code of ['C1','C2','C3','C4','C5']){const c=raw?.competencies?.[code],score=Number(c?.score);if(!Number.isInteger(c?.score)||!VALID_SCORES.has(score)) throw new Error(`Pontuação inválida em ${code}.`);comps[code]={score,diagnostic:String(c?.diagnostic||''),strength:String(c?.strength||''),improvement:String(c?.improvement||'')}}
      const total=(Object.values(comps) as any[]).reduce((sum,c)=>sum+c.score,0)
      return {report_format:'essential-v1',main_strength:String(raw.main_strength||''),next_step:String(raw.next_step||''),protocol_version:QUALITY_VERSION,scoring_calibration:SCORING_CALIBRATION,syntax_assessment:raw.syntax_assessment,reading_notes:raw.reading_notes,proposal_complete:raw.proposal_complete,essay_status:raw.essay_status,zero_reason:raw.zero_reason,transcription:raw.transcription,c1_deviations:raw.c1_deviations||[],repertoire_checks:evidence.repertoire_checks,c5_check:raw.c5_check,paragraph_balance:raw.paragraph_balance,qa_summary:raw.qa_summary,improvement_priority:raw.improvement_priority,detailed_analysis:{report_format:'essential-v1',scoring_calibration:SCORING_CALIBRATION,main_strength:String(raw.main_strength||''),next_step:String(raw.next_step||''),c1_deviations:raw.c1_deviations||[],repertoire_checks:evidence.repertoire_checks,c5_check:raw.c5_check,paragraph_balance:raw.paragraph_balance,qa_summary:raw.qa_summary},preliminary:true,reading_quality:String(raw?.reading_quality||'partial'),needs_manual_review:raw?.reading_quality!=='good'||!!raw?.needs_manual_review,manual_review_reason:String(raw?.manual_review_reason||''),theme_adherence:String(raw?.theme_adherence||'partial'),motivating_text_copy:String(raw?.motivating_text_copy||'none'),competencies:comps,total_score:total,introduction_structure:String(raw?.introduction_structure||''),intervention_alignment:String(raw?.intervention_alignment||''),repertoire_productivity:String(raw?.repertoire_productivity||''),overall_feedback:String(raw?.next_step||raw?.overall_feedback||''),alerts:Array.isArray(raw?.alerts)?raw.alerts.map(x=>String(x)).slice(0,6):[],...evidence}
    }
export function extractOutputText(resp){for(const item of resp?.output||[]){for(const c of item?.content||[]){if(c?.type==='output_text'&&typeof c.text==='string') return c.text}}return ''}

